### ISSUE TITLE
consent: Share session state between login and consent

### ISSUE THREAD

**Issue by MOZGIII** [ory/hydra#1003]
**Do you want to request a *feature* or report a *bug*?**

It's kind of both.

**What is the current behavior?**

Accept login request API call does not allow setting extra `accessToken` data.
Get consent request does not provide `accessToken` data.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Just use the standard example nodejs app.

**What is the expected behavior?**

Accept login request API call allows setting extra `accessToken` data.
Get consent request provides extra `accessToken` data set when accepting login request.

**Which version of the software is affected?**

1.0.0-beta.8

**The story & rationale**

Hey guys, I have an issue with the new login/consent logic.

It was charged since v0.11, and we're now updating to v1.0.0-beta.8.

Now it first redirects the user to login request verification callback, and allows to set `subject` when accepting login request.
Then it assumes that the consent endpoint, given just the `subject` can provide the `accessToken` information when accepting the consent request.

This became problematic for us due to a disconnect between assigning the `subject` and extra `accessToken` data. The thing is, in our system, just the `subject` is not enough to fetch the internal user object, and therefore to get the context information. We put additional parameters (semantically similar to "region", or "rack id") in the `accessToken`, that allow us to reference the internal user.

This is why we simply can't fetch the user given just the `subject`, and can't properly perform consent (and assign `accessToken`).
It looks like a dead end to me.

There are possible workarounds to this issue, like storing the additional data in memory for the short period of time on the callback handler server side, but it's obviously broken and ugly, yet insecure.

Can we allow assigning extra `accessToken` data when accepting the login request, then accessing that data when reading consent request and reassigning them when accepting consent request?

**Comment by aeneasr** [comment]
So the issue is that the access token session data is (usually) coupled to the consent state, not to authentication. Personally, I see access token data as internal session data that should not be available to the outside world. The issue is that many people see this differently and want JWT with transparent session data. As we added JWT due to popular demand, the session data is no longer internal and should thus rely on the scopes that have been granted. Therefore, it makes most sense to set the session data during the consent acceptance.

We had an issue where we discussed that it would be great to set additional data ("metadata") during consent and login. This would allow the consent app to delegate state management to hydra instead of implementing a DB connectivity for this. Would this improve your situation?

**Comment by MOZGIII** [comment]
If you mean that instead of setting the `accessToken` I’ll be able to set and then read some other `metadata` field that would be not be shown anywhere in the JWT or token introspection - or even be available solely in the current authentication flow (and consequent “skipped” ones) - that would also solve the issue, as I could read that `metatada` at the consent callback and properly reference the the correct the user object.

However, I’m not sure that adding a generic thing to manage store (i.e. with an unrestricted flow of updates) is a great idea. My guess that having a “hidden” piece of data that you can assign when accepting login request and then read everywhere else where you can read the `subject` might be a simpler to maintain and less error prone thing.

**Comment by aeneasr** [comment]
> If you mean that instead of setting the accessToken I’ll be able to set and then read some other metadata field that would be not be shown anywhere in the JWT or token introspection - or even be available solely in the current authentication flow (and consequent “skipped” ones) - that would also solve the issue, as I could read that metatada at the consent callback and properly reference the the correct the user object.

The data would be available when

1. the same user is found during login dance (requires login.remember: true)
2. the same user is found during consent dance (does not require login.remember: true)

You're right however that writing to this store unhinged is prone to conflict. It's probably not such a great idea after all.

Another possibility would be to include the login challenge in the consent request payload. That way you could set up a store where you temporarily keep the data you need (the key would be the login challenge) and retrieve (and optionally delete) that data during consent by looking up the login challenge.

With that, you can implement what you're asking and we're not adding stuff to the hydra functionality that might work for some cases but not all.

**Comment by aeneasr** [comment]
I don't think it's that easy generalizable. Just off the top of my hat, I already see two distinctions:

1. You set data during login and it is available for the related consent request. If the user performs another OAuth 2.0 flow the data will not be available, unless you explicitly set it there as well.
2. You set data during login which is available for the remainder of the login session validity (if remember is true that's e.g. 30 days) to both login and consent. Assuming the user performs another OAuth 2.0 flow, the data will be available for both login and consent.

**Comment by MOZGIII** [comment]
For the case of just passing state from login to consent handlers we only need the first (1) option. (2) is something else, as it shares the session data. Might be useful too, but not clear when.

(1) with the skip mode should also allow access to data, so (2) is not needed in my opinion.

**Comment by aeneasr** [comment]
> (2) is not needed in my opinion.

Well...it's not needed for your use case, which is why I said that it's not that easily generalizable.

Nevertheless, I think including the login challenge during consent is a good start. We might even include the login session ID if it exists, that way you can persist data across multiple login requests. Storing the data for you isn't something I'd put on the priority list. First it's not something required for getting to 1.0.0 stable and second is that ORY Hydra isn't a datastore. I mean sure, we can have store a JSON object for you, but you can't query it. You can't update the schema. You can't migrate. You can't test it. I'm doubting if that would be a good idea. Your consent/login app is connected to a store anyways (where would you get your user data from otherwise?) so the added complexity of storing something along a key in a format that you see fit isn't something that is difficult to achieve.

**Comment by MOZGIII** [comment]
I'm trying to elaborate on the generic case, not just my case.
And I'm not saying that (2) is not needed in general, I mean that it's not need to pass the data from login to consent because it's solved by (1) already, and that (2), being not bound to consent/login session but to just login session, is something else.

I didn't mean to say I know what's needed and what's not, sorry if I miscommunicated that.

Definetly, adding logic challenge is a good idea. :) But for me it doesn't improve the situation.

On the other hand, if we had both login challenge and the ability to store metadata in the login request record, I could fetch login request from the consent endpoint and it would solve my issue.

**Comment by MOZGIII** [comment]
It's also true that we can add a database on our end. I just hope to find a way to keep this part stateless, because we already have a database for hydra, but the datastore for our "users" is kind of specific, so it's not a good option for us to extend that. Probably, therefore, our use case it's not that important for hydra - it's very restrictive. Although, I'm sure there are a lot like it in the wild.

**Comment by aeneasr** [comment]
> I didn't mean to say I know what's needed and what's not, sorry if I miscommunicated that.

No need to apologize. I may sound harsh sometimes, but that's just my German nature ;)

Ok, I think the first actionable item will be to add the login challenge to the consent payload so we can track this across requests. Regarding storage of metadata, I really have to think about this. As I said in the previous comment, I see a lot of downsides to this. But maybe I can come up with something that eases those concerns! Please note though that this isn't high priority as there's a ton of stuff currently on my / our plates. If you need this rather soon, either work out a proposal for a PR or drop a line to hi@ory.sh to figure something out. Cheers!

**Comment by MOZGIII** [comment]
Thnaks, @aeneasr. It's not urgent for us, since we implemented workaround already (we're pretty tight on time with this upgrade, so we were willing to exchange time for tech debt).
Looking to forward to help with elaborating, hope we'll be able to remove our workaround.

**Comment by aeneasr** [comment]
We added `login.session_id` and `consent.login_session_id` as well as `consent.login_challenge` which allow you to link the request to one another. The store you requested will not make it in the product because of the issues I mentioned.

**Comment by MOZGIII** [comment]
Good start, thanks. This will improve the situation.

**Comment by MOZGIII** [comment]
Still hoping to see a proper solution though.

**Comment by struhtanov** [comment]
I have very similar problem. I'm working on multi-tenant application, where tenant is retrieved from host. Similar to slack, where you go to _a.slack.com_ or _b.slack.com_, depending on your organization. 
I want to have one url to give to my oauth clients. Let it be auth.slack.com (in our slack example). When client is redirected to login-consent app(by hydra), I show screen to select organization. After that I redirect user to login screen, then to consent screen. In the end I want to put information about  organization that user has entered into oauth token(using `session` field of `acceptConsentRequest` params). When client is making requests to my server with oauth token in headers, I can check if organizations in the token and in the url match.

Similar to @MOZGIII I need somehow store information between login and consent requests. In my case I want to store information about selected organization. As everything is going through hydra by redirects, I have no other options than to store some kind of session in my login-consent app. This looks error-prone to me, because hydra has session (using cookies) and it could be possible that I'm redirected to consent screen without visiting login screen(because there is already session in hydra). So there will be no place to get organization info.

**Comment by aeneasr** [comment]
Ok, let's reopen this - feel free to PR (please discuss the changes first in this issue).

**Comment by MOZGIII** [comment]
I'd just want login and consent flow to be stateless. I mean, we don't even have a meaningful consent semantics - but we still need to push the extra fields for the introspection to return for token. Would work best if we just could pass them from the login endpoint.
How about supporting two integration flows? This sounds bad, but maybe it's not really that bad.

**Comment by aeneasr** [comment]
Why don't we add another field to the `/login/:challenge/accept` endpoint with `metadata json.RawMessage` which is then returned at `/consent/:challenge` as `login_metadata`? I don't think this should persist though but be individual metadata for every login&consent flow

**Comment by MOZGIII** [comment]
But then with autologin you won't be able to use that metadata.

**Comment by aeneasr** [comment]
The login endpoint would have to resend the data. Keep in mind that every login request is being forwarded to the login endpoint, regardless of remember state.

**Comment by uttaravadina** [comment]
@MOZGIII thanks for creating the issue. I encountered a similar problem where a user's data retrieved from `login` stage, when using an external login provider, is to be put into the `session` object which is set in the consent stage.

@aeneasr is pushing towards the zero-trust system. So it makes total sense to avoid this store in the hydra in the first place. It's better to store that state externally and take full responsibility for it. 

Here's my 2 cents on Pros and Cons of having a store inside the hydra:

Pros: 
Having a store between the login and consent can reduce the overall number of API calls required to build a context whenever a 3rd party wants to access a resource server as the session data can be stored in the `session` object during the `consent` phase.

Cons: 
If and when the session data gets invalidated, outdated or modified, it's a whole new complexity to update that specific user's session data in the current session tokens already available to the 3rd parties. It will cause much more damage and breakouts.

The sole purpose of that `session state` is to reduce the complexity of building a context so that whenever a 3rd party is trying to access a resource server that server knows what to do with the necessity of fetching a user/subject's state from another resource server.

It's better to have a store outside the hydra and use cache mechanisms which can be invalidated an updated at will. That way the ability to invalidate/update the User's session data, required by a resource server, can be robust, deterministic and less complex. You can use something like ory/oathkeeper to inject state data into the HTTP headers for specific subject/user soon after the token introspection.

@aeneasr let me know your thoughts on this.

**Comment by uttaravadina** [comment]
@struhtanov would it be possible for you to make the User login first and then ask the organisation the User wants to give access to in the Consent Page itself? That way the `subject` is covered in the `login phase` and `organisations` can be put into the `session object` in the `consent phase`.

**Comment by aeneasr** [comment]
The issue was closed because the feature was implemented.
