### ISSUE TITLE
Intro Blog source code is unreadable

### ISSUE THREAD

**Issue by paytonrules** [ory/hydra#1111]
**Describe the bug**
I can't find another place to put this - your blog doesn't have comments - but the introductory blog's source code highlighting is unreadable on Chrome and Firefox on Mac.

Feel free to delete this, but a twitter mention seemed like the wrong way to inform you.

**To Reproduce**
Look at the blog https://www.ory.sh/run-oauth2-server-open-source-api-security/

**Expected behavior**
Readable text

**Screenshots**

<img width="435" alt="run_your_own_open_source_oauth2_server_-_step_by_step_guide" src="https://user-images.githubusercontent.com/21752/47370746-03b96200-d6ac-11e8-8bf7-cdea53ad1b96.png">

**Version:**
 - Environment: Chrome or Firefox
 - Version latest

**Comment by aeneasr** [comment]
Man, I don't know what's up with that. it seems to break randomly but always works locally. In any case, thank you for reporting.

**Comment by aeneasr** [comment]
I think I finally figured it out, when hard-reloading the page the text is dark, when browsing there from the "blog" section it's not, I'll try to fix it asap

**Comment by aeneasr** [comment]
For some reason, netlify chose not to update the CDN any more which caused react to try and render unknown nodes which caused react to not load at all which caused react-highlight not to run which was also caused by react-highlight not functioning with SSR (server-side rendering) which in fact caused the issue, along the not updating part. Anyways, I built a custom build pipeline around circle-ci and created a new netlify site which hopefully fixes all of those issues now. At least the color is back!
