### ISSUE TITLE
Login time deteriorates over time

### ISSUE THREAD

**Issue by s-kramer** [ory/hydra#1119]
**Describe the bug**
We're experiencing login time deterioration. The login time for one of our monitoring users which logs into the system periodically every 15 minutes for the last 2 weeks increases systematically and is now a little under 10 seconds. 
We can see in the logs that the request to "/oauth2/auth" sent during the login to Hydra lasts almost 10 seconds. During this period we can observe that almost 2000(!) queries are made to the database. There are only 2 distinct queries made during this time period:
`SELECT * FROM hydra_client WHERE id=$1` and `SELECT * FROM hydra_oauth2_consent_request WHERE challenge=$1`.

Number of selects is strictly connected with `select count(*) from hydra_oauth2_consent_request WHERE subject=?;` value.

Hydra log with time in nanoseconds:
```
{"level":"info","measure#https://XXXX":9797289959,"method":"GET","msg":"completed handling request","remote":"xxx.xxx.xxx.xxx:xxxxx","request":"/oauth2/auth?client_id=XXXX...","status":302,"text_status":"Found","time":"2018-10-23T08:59:14Z","took":9797289959}
```
For newly created users the issue does not occur - there are only a few DB calls made during the same request.

**To Reproduce**
1. Log into the system
2. Track login time
3. See error

**Expected behavior**
The login time is not changing between logins.

**Version:**
 - Environment: Docker, Kubernetes, Postgres (unmodified Hydra Docker image)
 - Version hydra:v1.0.0-beta.8-alpine, PostgreSQL 10.1 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18) 6.3.0 20170516, 64-bit

**Additional information:**
Response times from hydra in nanoseconds:
```
/oauth2/auth?client_id=xxx1    9908294554
/oauth2/auth?client_id=xxx2    718322749
/oauth2/auth?client_id=xxx3    284450599
/oauth2/token   200575225
/oauth2/revoke  154315033
/oauth2/auth?client_id=xxx4     100506219 
```

**Comment by aeneasr** [comment]
Interesting, this could be caused by missing indices as well as a missing boundary (`LIMIT`) when scanning for existing login or consent sessions. There's a PR for setting up open tracing spans that also screen query time which make this much easier to debug (#1105). Do you think it would be possible to run that with jaeger and see what exactly causes the long response time?

For a quick remedy, you can try (first back up) and remove all sessions related to that user (USE AT YOUR OWN RISK):

* `DELETE FROM hydra_oauth2_authentication_request_handled WHERE subject=<the-user-id>`
* `DELETE FROM hydra_oauth2_authentication_session WHERE subject=<the-user-id>`
* `DELETE FROM hydra_oauth2_authentication_request WHERE subject=<the-user-id>`

This MAY take some time depending on the size of your DB because `subject` doesn't have an index.

**Comment by dlienko** [comment]
Yes, looks like `FindPreviouslyGrantedConsentRequests` is the problem.
But how we can use any limit? What if the given consent we are looking for is 51st?

**Comment by aeneasr** [comment]
Hm, I'm also a bit confused because the query looks for previous requests where `remember=true` but `skip=false`. This *should* only apply to consent requests where no previous consent was given (e.g. wrong set of permissions/scope) but it seems like that's not the case here. Maybe because the application is using `prompt=consent` always but `remember=true` in the consent app?

**Comment by aeneasr** [comment]
Typically, in regular scenarios and over the lifetime of a user in a system, this shouldn't be more than a couple of requests (maybe 10). I don't quite remember when I re-authorized a GitHub Application for example. For CI tools like CircleCI that's *at most* 2 or 3 times.

**Comment by aeneasr** [comment]
In any case, adding a limit here will fix that. If we're looking for the 51st consent request that's not a big issue because the worst that can happen is that the user is shown the authorization screen again. That might be a bit inconvenient but if the issue is as I suggested `prompt=consent` then the scope will not change, so this will be a very rare/exceptional case and the worst that happens is that the user gives permission again, which is sometimes even considered good security practice.

**Comment by dlienko** [comment]
We do send `remember=true` for the mentioned user (in fact, for this particular client).

I'm not that familiar with the Hydra code and golang itself, but I'm just thinking: `FindPreviouslyGrantedConsentRequests` is used ultimately for `matchScopes`. Would it be enough to store the set of ever consented scopes per user rather than the whole history?

**Comment by aeneasr** [comment]
> I'm not that familiar with the Hydra code and golang itself, but I'm just thinking: FindPreviouslyGrantedConsentRequests is used ultimately for matchScopes. Would it be enough to store the set of ever consented scopes per user rather than the whole history?

Yes, it would however be the equal to setting `LIMIT 1` as we would always take the most recent view. IMO that's actually enough.

**Comment by dlienko** [comment]
Just to be sure: only the recent consent counts? Or any ever given consent? :)

**Comment by dlienko** [comment]
RIght.

Could you please also describe the difference between `FindPreviouslyGrantedConsentRequests` and `FindPreviouslyGrantedConsentRequestsByUser`?

Any reason why the latter one has `LIMIT ? OFFSET ?` and not the former?

**Comment by aeneasr** [comment]
https://github.com/ory/hydra/issues/1119#issuecomment-432683668 sums up the reasoning for it, but as I said that's definitely a bug and not what we want here. The other method lists previous consents regardless of the client, so that might be more than 50, depending on how many apps have been granted, which is why a limit here made "more sense".

**Comment by dlienko** [comment]
Thanks for the explanation and fast responses :)
