### ISSUE TITLE
metrics: Add prometheus metrics

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#1176]
* https://github.com/zbindenren/negroni-prometheus
* https://github.com/slok/go-prometheus-middleware

**Comment by kminehart** [comment]
I started typing up a comment and then accidentally closed my browser. :(

I'll be working on this one over the next couple weeks.

I'll be using https://github.com/slok/go-http-metrics to instrument basic HTTP metrics like request count, duration, response statuses. That should be sufficient for measuring Hydra's performance and reliability.

I'll be using the normal prometheus go client to instrument some hydra specific metrics.

I'll need some input as to what metrics should be measured.

Some ideas (after discussing with @aeneasr ):

* # of clients
* # of JWTs
* # of access tokens
* # of active refresh tokens
* # of refresh tokens
* # of authorize codes
* # of id tokens

---

Implementation:

* We need to be careful [not to overuse labels](https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels).
* Querying for these metrics in the databbase might cause slow responses, and high scrape intervals could cause data to not be returned at all.
  * Keeping up with this data as it's created / deleted instead of querying the databbase could cause problems with synchronization, especially if Hydra is restarted.

Some good articles by one of the Prometheus authors:

* https://www.robustperception.io/why-predeclare-metrics
* https://www.robustperception.io/existential-issues-with-metrics

Personally, after doing some thinking, as long as we're smart about how the metrics are retrieved from the databbase, then I see no reason why querying the database would be a huge issue. :)

**Comment by aeneasr** [comment]
Sounds great! I think there are a couple of metrics we'd be able to extract:

- Client:
  - Number of clients in the datastore
- JWK/Keys:
  - Number of JWKs in the datastore
- User login & consent:
  - Number of unique users that performed the flow in the last X m/h/d/w/y
- OAuth 2.0:
  - Number of total active access tokens
  - Number of total refresh tokens (a refresh token can not be inactive as it will be removed from the datastore once used)
  - Sum (increase/counter) of access tokens issued overall
  - Sum (increase/counter) of refresh tokens issued overall
  - Sum (increase/counter) of ID tokens issued overall
  - Number of token revokations for access tokens and refresh tokens
  - Number of grant types performed (authorize code, implicit, hybrid, client credentials)
  - Which scope(s) have been requested and which scope(s) have been authorized

**Comment by aeneasr** [comment]
There hasn't been any interest in this and we also have not yet needed it internally - closing this.
