### ISSUE TITLE
Proposal: Support External Cryptography Services

### ISSUE THREAD

**Issue by jgiles** [ory/hydra#1328]
This is a meaty proposal, but I would like to start the conversation. If ORY is amenable to the idea, we might be able to contribute implementation help.

**Is your feature request related to a problem? Please describe.**
We generally avoid distributing + using long-lived private key material outside of Hashicorp Vault or AWS KMS. We would like to use one of these services, along with their utilities for key rotation, in place of Hydra's current secret management.

**Describe the solution you'd like**
It would be great if Hydra/Fosite supported external cryptography services as an alternative to reading private key material from env vars and performing keyed crypto operations in-process.

Example services:
 - Hashicorp Vault’s Transit backend
 - AWS KMS
 - GCP KMS

These services would simplify Hydra/Fosite key management:
 - Secure handling of private key material is offloaded to the external cryptography service. Hydra/Fosite just needs to be run with permissions to perform the specific cryptographic functions it needs with the keys held by the external service.
 - Possibly simplified key rotation (currently a bit painful in Hydra/Fosite), since many services provide rotation as a first-class behavior.

Because of these two advantages, many organizations are moving crypto operations to dedicated services where possible as a matter of policy.

From an implementation perspective, this proposal would likely mean putting the crypto operations performed by Hydra/Fosite behind some interface, and injecting either the standard in-process or the specified out-of-process crypto implementation of that interface based on configuration at startup.

There is one additional concern with an external-service-based solution, which might motivate a change to the issuance, storage, and verification scheme for token credentials. Hydra/Fosite generally uses keyed HMACs for token integrity, and (if I understand correctly) stores HMACs in the DB for later lookup when needed. In an external-service implementation, this symmetric signing scheme puts a call to the external service (“HMAC `token` using key X”) in the “hot path” of credential verification on every API request.

This is undesirable for a couple reasons:
 - Latency, since it introduces an external service call on every token verification.
 - Load on the cryptography service. For AWS/GCP this is likely just a billing impact, but for the Vault transit backend this load would contend with other traffic to a critical piece of infrastructure.

You could mitigate both issues by doing some caching of credential verification results somewhere, but that too is non-ideal.

Rather, it would be preferable to use an asymmetric public-key signing scheme to enforce token integrity when using external cryptography service:

1. On credential issuance, Hydra/Fosite calculates a plain hash of the token, calls “sign `hash` with key X” on the external service, and stores both the hash and the signature in the database
2. On credential verification, Hydra/Fosite calculates the plain hash of the token, looks it up in the database, and verifies the stored signature against the known public key of key X in-process.

This scheme maintains the cryptographically-enforced integrity guarantees of the current HMAC scheme, but keeps verification in-process even if all private-keyed crypto operations are pushed out-of-process.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by aeneasr** [comment]
Thank you for starting the conversation here. This topic has come up before.

> Possibly simplified key rotation (currently a bit painful in Hydra/Fosite), since many services provide rotation as a first-class behavior.

Totally agree, which is why this will become much, much, much easier with #1314 

> Rather, it would be preferable to use an asymmetric public-key signing scheme to enforce token integrity when using external cryptography service:

This sounds rather intriguing and definitely doable by replacing HMAC SHA256 with RSA SHA 256 (or adding it as an alternate strategy). In general I do not like the idea of requiring external dependencies due to simplicity, especially if we're talking about direct dependencies on proprietary, vendor-specific APIs (AWS/GCP KMS). Rather, I'd like to see an approach that enables both - an internal service that is as secure as those upstream services using HMAC-SHA256 and one where we offload this to a third party. One thing that's important to me/us though is that we do not want to maintain a lot of external adapters. Just adding GCP KMS, AWS KMS and Hashicorp Vault will significantly increase complexity in testing and QA as it will be difficult to set up tests and ensure compatibility with e.g. future versions of Hashicorp Vault. Any ideas here how to keep maintainance effort as low as possible?

What's also important to keep in mind is that there are several places where cryptography is being used:

- Token issuance (Access, Refresh, Authorize) using a symmetric key
- Token issuance (ID Token) using an asymmetric key
- Cookie issuance using a symmetric key
- Encryption-at-rest of private/public keys using AES-GCM with a symmetric key

Completely removing cryptography from Hydra will thus be a work-intense task.

**Comment by aeneasr** [comment]
Closing due to lack of public interest.
