### ISSUE TITLE
Why is my BCrypt benchmark slower than CircleCI's?

### ISSUE THREAD

**Issue by leonfancy** [ory/hydra#1478]
**Describe the bug**

I did performance test using the[ scripts/run-bench.sh](https://github.com/ory/hydra/blob/master/scripts/run-bench.sh) as what the Hydra [CircleCI here](https://circleci.com/gh/ory/hydra/8530) did. 

I set up a clean VM in Azure, the VM type is Standard DS2 v2 (2 vcpus, 7 GiB memory). Then I install go 1.12.6, the rakyll/hey and latest version Hydra. Then I ran the `scripts/run-bench.sh`. 

Here is my result: 
![image](https://user-images.githubusercontent.com/4530475/59914336-c41a6400-944c-11e9-8481-8fda7aae7ced.png)

The throughput is 87 TPS and average latency is 1.08s, which is much worse than what you listed here (500.9696 TPS, 0.1915s latency): https://www.ory.sh/docs/next/performance/hydra#client-credentials-grant.

I also tested on DigitalOcean's VM, the result is almost the same.

I use same 2 CPU cores as you, why my performance is much much worse than you? 

**Environment**

* Version: 1.0.0_rc16
* Environment: Azure VM Standard DS2 v2 (2 vcpus, 7 GiB memory)

**Comment by aeneasr** [comment]
This is the third (or fourth?) issue you're opening regarding BCrypt performance. Unless you're running into production issues with this please refrain from opening further issues. So far, all of your reported performance issues were caused by unrealistic scenarios. Running 500 TPS on the Client Credentials endpoint is an unrealistic scenario, unless you're dealing with scales in the realm of Digital Ocean, GitHub, or other big cloud providers, in which case you can probably afford a couple more nodes.

BCrypt is intentionally slow. It is slow to make cracking of passwords infeasible. We use BCrypt to hash OAuth 2.0 Client Secrets. If you perform a lot of BCrypt operations (such as performing the Client Credentials Grant), the CPU will be working a lot and once you hit 100%, it will take some time to process the operations, thus decreasing the TPS.

What you're really asking here is: Why is my BCrypt performance on Azure slower than the ones you run in CircleCI? Well, I don't know to be honest, but here are some guesses:

- The Azure vCPU is particularly bad at computing BCrypt hashes
- You are using a higher BCrypt cost value. The higher the cost, the longer the request takes, and the less RPS you get.

ORY Hydra is running in really large deployments, serving deployments that handle real traffic of up to 200rps **on average**. While there have been minor incidents of e.g. database keys missing, which we resolved quickly, noone has ever complained about BCrypt performance.
