### ISSUE TITLE
CORS allowed_origins not working as expected

### ISSUE THREAD

**Issue by davideferre** [ory/hydra#1615]
After many retries I found that _Origin_ header is requested to get correct CORS headers.
In one of this retry in my configuration file I've specified _allowed_origins_ as _http://*_ and I've created a client with _allowed_cors_origins: ["http://*"]_. When I call (from postman) _./well-known/jwks.json_ url specifying _Origin: http://127.0.0.1:4200_, CORS headers are missing, but when I specified _Origin: http://*_ it worked.

**Reproducing the bug**
I've tried with 1.0.2 version and 1.0.8 version but the bug is still present. See attached configuration.

*Server configuration*

cors:
      enabled: true
      allowed_origins:
        - http://*
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type

**Environment**

* Version: v1.0.8
* Environment: Ubuntu, Docker

**Additional context**

For get it working I've to specify _allowed_origins: http://localhost:4200_ in server configuration and _"allowed_cors_origins": ["http://127.0.0.1:4200"]_ into the client.

**Comment by aeneasr** [comment]
Yes, that's how CORS works: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Without `Origin` in the HTTP header, the whole CORS idea is baseless. If you use Postman to emulate a browser, you need to behave like a browser - which, when using CORS, consists of (among others) setting the right `Origin` header.

**Comment by davideferre** [comment]
I'm not sure if hydra is working properly because if I specify **allowed_origins** as **http://*** I would expect that with **Origin:http://127.0.0.1:4200** headers the CORS are working fine but this didn't happen.

**Comment by aeneasr** [comment]
Okay, I think I misundestood what you said! So it appears that `http://*` is parsed as a literal string as opposed to a wildcard when using `allowed_cors_origins` in the client?

**Comment by davideferre** [comment]
Correct!

**Comment by aeneasr** [comment]
Got it, thanks! Triaging as bug/client.

What I don't really understand is, we actually have a test case covering your bug report:

https://github.com/ory/hydra/blob/95a51deb3100034db5c6d98bbd7838a3b43249ce/driver/cors_test.go#L92-L100

https://github.com/ory/hydra/blob/95a51deb3100034db5c6d98bbd7838a3b43249ce/driver/cors_test.go#L92-L100

The only test case I couldn't find and taht would co-incide with your report would be where both the global config and the client config are using a wildcard.

Alternatively, it could be cause you're using `http://*` instead of `http://*.something` which might break the following lines and is also not covered by tests:

https://github.com/ory/hydra/blob/95a51deb3100034db5c6d98bbd7838a3b43249ce/driver/cors.go#L119-L125

Would you be open to checking this out and submitting a PR or info with your findings?

**Comment by Aterocana** [comment]
Hello, I'm proposing this solution: https://github.com/Aterocana/hydra/commit/5d7cf583def1c4961ef3eb27cfba8da3b9e2075c with [this pull request](https://github.com/ory/hydra/pull/1623)
Basically I think the issue here is the protocol is specified, but no domain is: for example https://*.
Internally glob.Glob is compiled (with glob.Compile) with the provided string and `'.'` rune separator. Since `g:=glob.Compile("https://*", '.')` doesn't match `g.Match("http://foobar.com")` due to `.` separator, we could use `g:=glob.Compile("https://**", '.') to ignore `.` separator in this specific case.
In order to do so I simply tried to match if "://" substring is into an allowed-origin string.

**Comment by aeneasr** [comment]
Ohh, yes, that makes a ton of sense!
