### ISSUE TITLE
Support for OAuth2 Dynamic Client Registration RFC (7591, 7592)

### ISSUE THREAD

**Issue by timkelley-ingage** [ory/hydra#1616]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

To support the OAuth2 dynamic client registration specification and the client management specification, there are a few features that need to be implemented in ORY Hydra:

Extension parameters:
- RFC 7951 states: 
> Extensions and profiles of this specification can expand this list
   with metadata names and descriptions registered in accordance with
   the IANA Considerations in Section 4 of this document.
- Also referenced [here](https://tools.ietf.org/html/rfc7591#section-3.1)
- Specific extension parameters that I think would be very useful that also impact token generation are for the capability for each client to have defined access and refresh token expiration times.  It would provide the ability to make it longer for specific clients and maybe shorter for specific use cases.

registration_access_token:  This field is used to validate a request when performing an operation on a client.  It is described [here](https://tools.ietf.org/html/rfc7592#section-3) in the RFC, and referenced under each endpoint in the client management.

**Describe alternatives you've considered**

N/A

**Additional context**

In order to fully support OAuth2 protocols, it is necessary to have these RFC's implemented.  It will allow ORY Hydra to be an even more feature-rich product.

**Comment by aeneasr** [comment]
Why is OpenID Connect Dynamic Client Registration not sufficient?

**Comment by timkelley-ingage** [comment]
There are a few reasons, which I outlined above:
1. The OAuth2 RFC mentions specifically the capability for adding custom extension parameters to client metadata.  I had considered the possibility of making a generic way for adding custom attributes (via key/value pairs) to the client information in Hydra to support custom applications.  The main driver for having this in the client itself is that it makes it possible for the Login/Consent provider to use that information.
- Going along with this, the custom token expiration times per client I mentioned above might be a nice feature to add as well.
2. The registration_access_token discussed in the OAuth2 RFC adds in additional security around accessing and modifying client information.  This helps prevents attackers from attempting to access/modify client information while only having the client_id value.

**Comment by aeneasr** [comment]
> The OAuth2 RFC mentions specifically the capability for adding custom extension parameters to client metadata.

#1602 

> Going along with this, the custom token expiration times per client I mentioned above might be a nice feature to add as well.

> The registration_access_token discussed in the OAuth2 RFC adds in additional security around accessing and modifying client information. This helps prevents attackers from attempting to access/modify client information while only having the client_id value.

The current `/clients` endpoint __is unprotected__. Exposing it as-is to the outside world is insane and will corrupt the integrity of your system. Whenever you chose to expose this endpoint to the public, you will need to make sure to secure it *with a method you seem suitable*. That can be either an access token issued for that client (using oathkeeper to protect it, or kong + plugin, or ...), using the client id and secret for that client (using oathkeeper, or kong, ...). We chose this method (no default protection mechanism) over a forced one to allow for maximum flexibility.

Therefore you can achieve what `registration_access_token` is doing by configuration with the system as it stands today.

> Going along with this, the custom token expiration times per client I mentioned above might be a nice feature to add as well.

This is a separate concern and not covered by the RFC's. In fact, we've discussed this in several issues. In most use-cases, this is something people want when they in fact want to use API Keys (or "Personal Access Tokens", which are API Keys), which is not what OAuth2 solves. Therefore the consensus is that this is not a feature likely to be added unless further evidence is provided, and if implemented, it would be added to the existing OIDC DCR, which also allows specifying additional keys.

> Additional Client Metadata parameters MAY also be used. Some are defined by other specifications, such as OpenID Connect Session Management 1.0 [OpenID.Session]. 

https://openid.net/specs/openid-connect-registration-1_0.html

**Comment by ioneyed** [comment]
Since OIDC's DCR SHOULD be following the OAuth2 DCR RFC we could concede on that in this ticket but the DCR Management which is an implementation consideration for OIDC still adds value to proceed. 

> The current /clients endpoint is unprotected. Exposing it as-is to the outside world is insane and will corrupt the integrity of your system. Whenever you chose to expose this endpoint to the public, you will need to make sure to secure it with a method you deem suitable. That can be either an access token issued for that client (using oathkeeper to protect it, or kong + plugin, or ...), using the client id and secret for that client (using oathkeeper, or kong, ...). We chose this method (no default protection mechanism) over a forced one to allow for maximum flexibility.

You are correct, it is insane to open that endpoint up without any protection. In the pursuit of being flexible the specification driven "forced" approach (which is still flexible while adding protection) is being proposed. The RFC for Dynamic Client Registration Management (https://tools.ietf.org/html/draft-ietf-oauth-dyn-reg-management-05) which is the draft that is stated as a "Implementation Consideration" of the OIDC DCR specification. This DCR Management Specification is now in draft 15 but it has a way to secure that endpoint with a layer of security. This layer can be enforced if no token/client_id+secret combo is present in the request but can also be used without the client_id/secret. The `registration_access_token` can be leveraged in generic applications such as a developer portal to further secure the endpoint so that compromised credentials from OAuth2 Apps do not allow mass update to the registered OAuth2 applications if a combination of oauth2+registration_access_token is enforced (which could be a configuration value providing flexibility with a default of "off") 

>Implementations wanting to support additional operations defined in OAuth 2.0 Dynamic Client Registration Management Protocol [I‑D.ietf‑oauth‑dyn‑reg‑management], draft -05, such as Update, can do so using that specification, while being mindful that the specification is a work in progress, and may change.

^ https://openid.net/specs/openid-connect-registration-1_0.html#ImplementationConsiderations


>In fact, we've discussed this in several issues. In most use-cases, this is something people want when they in fact want to use API Keys (or "Personal Access Tokens", which are API Keys), which is not what OAuth2 solves.

This is not the case for ALL scenarios.. We have scenarios where we want to utilize the same Identity Provider (token minting) for different aspects of our business that require stricter security controls. With the ability to utilize the meta data we could generate tokens with different expiry times based on risk considerations of the data that they can retrieve as well as their "footprint" to our business. It doesn't make sense to stand up many Identity Providers with slightly different configurations as it just grows our security vectors without adding much benefit when it can be achieved in a single solution.

**Comment by aeneasr** [comment]
> The registration_access_token can be leveraged in generic applications such as a developer portal to further secure the endpoint so that compromised credentials from OAuth2 Apps do not allow mass update to the registered OAuth2 applications if a combination of oauth2+registration_access_token is enforced (which could be a configuration value providing flexibility with a default of "off")

Yes, that is something that makes a lot of sense IMO. Personally, I'm not a fan of the way the IETF spec does that because it forces you to store yet another token for long-term use. Instead, I think that the following makes sense:

- No security required because exposed only internally
- Internal security required with e.g. mTLS (istio)
- Public exposure of the endpoint protected the OAuth2 Client ID + Secret
- Public exposure of the endpoint protected with OAuth2 Access Token from that specific client
- Public exposure of the endpoint protected with OAuth2 Access Token from that specific client and/or administrative users

I think that using an access token or client id + secret for accessing that endpoint makes much more sense, as you're using credentials you have anyways for managing said client. While one could argue that you can't reset the secret if you lose it, the same would apply if you lose the registraiton access token.

In conclusion, I'm not convinced that implementing this spec is worth the effort. Instead it would make sense to have a sane default config for Oathkeeper to provide any (maybe not the istio one) configs from above instead.

> This is not the case for ALL scenarios.. We have scenarios where we want to utilize the same Identity Provider (token minting) for different aspects of our business that require stricter security controls. With the ability to utilize the meta data we could generate tokens with different expiry times based on risk considerations of the data that they can retrieve as well as their "footprint" to our business. It doesn't make sense to stand up many Identity Providers with slightly different configurations as it just grows our security vectors without adding much benefit when it can be achieved in a single solution.

This is appreciated but may I suggest issuing this in another (either existing, not sure if one exists, or new) issue to keep the discussion going and allow for better searchability? I'm happy to answer in more detail there.

**Comment by ioneyed** [comment]
>Yes, that is something that makes a lot of sense IMO. Personally, I'm not a fan of the way the IETF spec does that because it forces you to store yet another token for long-term use. 

I would urge the consideration of a specification because tools that already implement the specification or new tools that can work across implementations can be built instead of knowing the "nuances" of one implementations opinions. This is a growing issue within the OAuth2/OIDC space because the specifications leave it to having too many 'SHOULD" and "OPTIONALS" that teams neglect to even offer based on their opinions. 

> Instead, I think that the following makes sense:
> * No security required because exposed only internally
This is crazy that anyone would leave it without security even internally since there number of disgruntled/malicious internal users that are part of data breaches.

> * Internal security required with e.g. mTLS (istio)
mTLS is only to ensure that 1 service can talk to another unless you are stating that each registered client gets their own TLS to achieve mTLS (why not just use the registration token instead?) If you are just securing WHAT can access the server this is not protection for WHO can access it.
> * Public exposure of the endpoint protected the OAuth2 Client ID + Secret
This doesn't prevent compromised OAuth2 credentials, registration_access_token doesn't prevent this but it can be seen as a second factor and should be handled more securely. 
> * Public exposure of the endpoint protected with OAuth2 Access Token from that specific client
Understandable but a user token from that client would be able to manipulate the registered application.
> * Public exposure of the endpoint protected with OAuth2 Access Token from that specific client and/or administrative users
Even if you make specific administration scopes you still have an endpoint that can be abused by a single factor of credentials that can be compromised. With the registration_access_token alone you exhibit the same problem except it is limited to a single application instead of every application. 

Based on the specification and what it's purpose is I feel that having a set of strategies for the ORY product (to enable flexibility) that include some of the options above as well as having the support for the registration_access_token gives your customers (ORY operators) the most flexibility and security based on their scenario.

**Comment by aeneasr** [comment]
> This is crazy that anyone would leave it without security even internally since there number of disgruntled/malicious internal users that are part of data breaches.

Depends on the threat model, as always.

> I would urge the consideration of a specification because tools that already implement the specification or new tools that can work across implementations can be built instead of knowing the "nuances" of one implementations opinions. This is a growing issue within the OAuth2/OIDC space because the specifications leave it to having too many 'SHOULD" and "OPTIONALS" that teams neglect to even offer based on their opinions.

That's the thing, OpenID Connect DCR is a spec that's well tested and certified. To my knowledge, no actual client code is implemented in any programming language (I might be mistaken) for this spec **albeit** the spec being final. I'm highly supsicious that the IETF spec is done.

> mTLS is only to ensure that 1 service can talk to another unless you are stating that each registered client gets their own TLS to achieve mTLS (why not just use the registration token instead?) If you are just securing WHAT can access the server this is not protection for WHO can access it.

One service for managing "developer accounts" talks to Hydra. This is how basically all OAuth2 Providers (GitHub, Google, ...) are doing it. Especially with things like "additional metadata" - which was one of your requests - this makes a lot of sense as some options are not somethign you'd like to expose to be modifyable by the public.

> Understandable but a user token from that client would be able to manipulate the registered application.

So? If your access control allows that that's fine - e.g. a admin user. For clients, it would obviosuly be only clients can modify themselves (unless defined otherwise in access control).

> Even if you make specific administration scopes you still have an endpoint that can be abused by a single factor of credentials that can be compromised. With the registration_access_token alone you exhibit the same problem except it is limited to a single application instead of every application.

There is no difference, maybe you misunderstood my points. And as always: depends on the thread model, security architecture, and access control patterns.

As you see, this is a very broad topic that can be solved in many ways, and if we enforce one way or another, there will always be people demanding another way. The approach we've chosen so far leaves that up to you. Granted, it's probably not the most straight forward thing when you set this stuff up, but this can be solved with bulletproof docs and examples, rather than forcing a specific way of doing things.

**Comment by aeneasr** [comment]
> What are your thoughts on the custom access_token_expiration and refresh_token_expiration attributes? I would want to propose adding those as separate attributes on the client outside of the metadata. The reason being that they will also need to be more integrated into the Hydra code when generating tokens. Do you think this could be a valuable feature? I can add them to the metadata at this point, but still would need custom logic for token generation.

> > This is not the case for ALL scenarios.. We have scenarios where we want to utilize the same Identity Provider (token minting) for different aspects of our business that require stricter security controls. With the ability to utilize the meta data we could generate tokens with different expiry times based on risk considerations of the data that they can retrieve as well as their "footprint" to our business. It doesn't make sense to stand up many Identity Providers with slightly different configurations as it just grows our security vectors without adding much benefit when it can be achieved in a single solution.
>
>
> This is appreciated but may I suggest discussing this in another (either existing, not sure if one exists, or new) issue to keep the discussion going and allow for better searchability? I'm happy to answer in more detail there.

**Comment by aeneasr** [comment]
I'm closing this issue because (a) has been resolved with the new metadata field (b) I've laid out several options on how to secure the clients endpoint and why we don't want to enforce a specific way of handling this and (c) I'd like to continue the discussion around expiry times per client in a new issue, where we can collect use cases and evidence without the noise from the other discussions going on here.

I'm tracking the OIDC DCR documentation here: https://github.com/ory/docs/issues/218
