### ISSUE TITLE
hydra-client-resttemplate: Provide authentication for all methods in the AdminApi

### ISSUE THREAD

**Issue by vmuth85** [ory/hydra#1628]
**Is your feature request related to a problem? Please describe.**

We have secured our administrative endpoints  by an Authorization Proxy. So the whole administrative port is secured by Basic Authentication. Because of this, all methods of the  AdminApi that, don't provide the Authorization header indicated by 
`String[] authNames = new String[] { "basic", "oauth2" };` 
won't work for us.
Although, I'm creating an ApiClient with a prefered authentication, the according Authorization  header will only be applied  to some specific methods.

**Describe the solution you'd like**
 I would be most pleased if the Authorization header would effect all methods in general, indicated by the authentication type and not for each method seperatly. So passing a username and password for instance, would provide the Authorization header to all methods.

```
ApiClient apiClient = new ApiClient();
apiClient.setBasePath(oAuthServerUrl);
apiClient.setUsername(username);
apiClient.setPassword(password);
```

**Comment by aeneasr** [comment]
Hm yeah that's a tricky one, because the swagger is actually correct - we don't need authentication here (and we want the docs to show that there is no authentication needed as well!). That however breaks the API Client because the code generator is so strict as to what should be applied and what shouldn't. OpenAPI Spec is really not that great for expressing open source technology that has different use cases.

I'm not sure how to approach this best at the moment.

**Comment by vmuth85** [comment]
Indeed, that is really tricky.

**Comment by aeneasr** [comment]
If you want you could try out other java code generators (maybe use https://github.com/OpenAPITools/openapi-generator instead of swagger-codegen) and see how those work? Unfortunately I don't write a lot of Java, this use case would be pretty easily solvable using Golang :/

**Comment by aeneasr** [comment]
I believe this is resolved with the new SDKs
