### ISSUE TITLE
Auth session cannot be prolonged even if the user is active

### ISSUE THREAD

**Issue by jimmytheneutrino** [ory/hydra#1690]
**Describe the bug**

The fix for #1557 changed the logic of when the session is killed. The hard timeout makes it now impossible to prolong the session even if the user is active and keeps refreshing tokens via silent refresh.

Could we reintroduce the possibility for the old behavior while keeping the new behaviour possible, too? In particular, it would be enough if setting rememberFor to a positive value on skipped login would still trigger the recreation of the session cookie. 
See the relevant line: https://github.com/ory/hydra/pull/1564/files#diff-daf069930bf5aee3faa0136e399ebaa2R433

This way, omitting the rememberFor on skipped login would result in the current behaviour (the old cookie is kept, max-age is not changed). But providing positive rememberFor would update the cookie with the new max-age, thus prolonging its life.

**Comment by aeneasr** [comment]
I think it would be better to set `RememberFor` to something large the first time the user authenticates that you can live with, such as a month, 6 months, or a year. It's typically a good idea to purge the cookie at some point. Wouldn't that too resolve your issue?

**Comment by jimmytheneutrino** [comment]
Not exactly. I want the session to die after a period of inactivity of, say, 4-6 hours. But not to die when the user is active. If I could reset rememberFor on skipped request, this could be easily achieved.

**Comment by aeneasr** [comment]
Right, that makes total sense!

The reason we disabled this behavior was because people might accidentally set `RememberFor` to some value always but do actually intend to not refresh the session every time.

Therefore, I think we should add another payload, something along the lines of `RefreshRememberTTL uint64 (or bool)` which would have the effect you want. Still trying to figure out if it should be the number of seconds as well, or if it should be a boolean which basically re-enables the `RememberFor` flag. Not sure at the moment about the naming, appreciate ideas!

**Comment by jimmytheneutrino** [comment]
I think, a more-or-less standard name for such a behavior is session `timeout` (e.g., server.servlet.session.timeout in spring boot). This could, in theory, be different from the total max-age of the session set by rememberFor.

**Comment by aeneasr** [comment]
Ok, tracking this - contributions are welcomed
