### ISSUE TITLE
Includes "jti" information in List Consent response

### ISSUE THREAD

**Issue by chaopeng** [ory/hydra#1694]
**Is your feature request related to a problem? Please describe.**

My user story is:
1. resource server logging: request resource RES with access token id: "ID-1" (jwt.jti), subject: "S-1" (jwt.sub)
2. resource server audit service: found security issues, notify user and account administrator, want to revoke token/consent with jti = "ID-1", sub = "S-1"
3. user or administrator use idp (built with hydra) portal:
  3.1. list all tokens, find the one with same jti delete, server call hydra -> [list consent by subject](https://www.ory.sh/docs/hydra/sdk/api#lists-all-consent-sessions-of-a-subject), find the consent has jti = "ID-1", revoke it
  3.2. or has a input box, revoke my token/consent with jti = "ID-1"

Similar to: https://github.com/ory/hydra/issues/304 and https://auth0.com/blog/blacklist-json-web-token-api-keys/

**Describe the solution you'd like**

What I want is a constant identity in a consent session which both included in access token and list consent response.

- I am not sure "jti" is the constant identity in a consent session.
- It still not easy for not jwt access token. use introspection endpoint to get the id (jti) and subject?

Currently, my workaround is add a custom claim `tokenid: new uuid` in access token session which is both included access token and list consent response and constant identity in a consent session.

**Comment by aeneasr** [comment]
The only way to revoke a token from the admin/audit side is to revoke application access because you will stop trusting the application as an administrator, not a specific token. This API is already implemented.

JTI is a concept only valid for JWT access token, which we [discourage you from using](https://www.ory.sh/docs/hydra/advanced#json-web-tokens). In fact, your use case, which looks to invalidate a specific JWT negates all the benefits you get from JWT, because you have to check with ORY Hydra on every request if the token is still valid or not. It's the same as using regular opaque Access Tokens!

A JTI is not a good identifier because the JTI, by definition, is different for every JWT, otherwise replay attacks are possible.

The linked Auth0 article talks about Personal Access Tokens, which are different from OAuth2 Access Tokens. Personal Access Tokens are API Keys and typically not issued to a third party. Additionally, Personal Access Tokens do not expire (usually).

OAuth2 Access Tokens are however issued to a third party, and they do expire. It is therefore difficult to revoke a specific OAuth2 Access Token.

The only thing I can think of is to revoke a specific consent session but I don't see a lot of benefit or use cases in revoking a specific consent session vs revoking the access to an application itself.

**Comment by aeneasr** [comment]
This is the API where you can revoke application access: https://www.ory.sh/docs/hydra/sdk/api#revokes-consent-sessions-of-a-subject-for-a-specific-oauth-20-client

**Comment by aeneasr** [comment]
No reply, closing.
