### ISSUE TITLE
Handle more than one client secret per client

### ISSUE THREAD

**Issue by DennisPattmann5012** [ory/hydra#1712]
**Is your feature request related to a problem? Please describe.**

If we want to rotate a client secret for a specific client, there is no way to have two client secrets in place for a specific time. Without this we have a synchronous dependency between client secret rotation and oauth client modification.

**Describe the solution you'd like**

We have the idea of adding a client secret struct like this:
```go
type clientSecret struct {
    clientSecretId: string,
    clientSecret:   string,
    createdAt:      time.Time(),
    validFrom:      time.Time(),
    validUntil:     time.Time(),
}
```
and pass this struct to client:
```go
type Client struct {
...
clientSecrets: [2]clientSecret
...
}
```

**Describe alternatives you've considered**

We have two other ideas, we thought of:
1. Adding a second client_secret directly to the client struct
We dislike this idea because we were missing the secret metadata (like validFrom and validUntil)
2. Make clientSecret in client to a slice of string
Rotation is nearly impossible because we wont know if a client secret is still in use

**Additional context**

We would love to work on a PR for that after we discussed the design of the feature

**Comment by aeneasr** [comment]
I don't think this would be compliant with OpenID Connect Dynamic Client Registration, right?

**Comment by DennisPattmann5012** [comment]
Didn't had this in mind.

What do you think about a new field like rotated_client_secrets that includes a client_secret struct? May you have some ideas?

**Comment by aeneasr** [comment]
Sorry for not replying. This is possible when using JSON Web Keys (private_key_jwt auth), as you can register more than one JWK per client. It is an advanced flow, but it’s also an advanced requirement :)

For secrets there is no standardized option and due to low community interest in the issue I am closing this issue, see reasoning below :)

I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️

**Comment by aeneasr** [comment]
Sorry, actually I noticed that we support this now in fosite. So it would be little work to add it here, if anyone is up for the challenge. First it would need an API proposal though!

**Comment by dpattmann** [comment]
Hi @aeneasr,

I'm still interested in this feature and would like to work on it.

About the API proposal, I'm not sure if it's necessary to touch the API, at least in a first version.

My idea is to update the client object/database to hold ```RotatedSecrets``` and add a new configuration option like ```SecretRotion : n``` for max ```n``` secrets. Default would be ```0``` to disable multiple secrets. 

When a client is updated via ```PUT|PATCH /clients{id}``` and RotatedSecrets is greater ```0``` the old secret will be moved to ```SecretRotion```.

What's your opinion?

**Comment by developerDemetri** [comment]
Hi, our team is also interested in this feature to enable graceful client secret rotations on a regular cadence.

My current Go knowledge is limited and I'm just starting to ramp up on Hydra. Probably not able to contribute quality features for a bit, but happy to help with this once I'm ramped up.

**Comment by nlochschmidt** [comment]
@zepatrik would it be possible to re-open this issue? The issue got marked as completed a long time ago. I think it was because it was still marked as stale. However, other issues and conversations about secret rotation are still pointing to this issue as the canonical one.

**Comment by alnr** [comment]
This is implemented in https://github.com/ory/hydra/commit/cdb582a8261e151f729347e4ddda8910692ffbbb
