### ISSUE TITLE
Biometrics authentication with Hydra

### ISSUE THREAD

**Issue by getavinashm** [ory/hydra#1742]
Hi All,
I am looking for a way to implement biometric authentication for my mobile app. The app uses Hydra for oAuth token but since the challenge would redirect the user to browser screen for entering credentials, I am looking for ways to allow biometric authentication and for user not having to enter the credentials manually.
Using refresh token could be one way I could think of but the refresh token again as a TTL and the authentication will not be seamless every time.
Please suggests anyway out of this.

Thank you.

**Comment by aeneasr** [comment]
I believe that biometrics are currently platform dependent (iOS, Android) and require an SDK for your mobile app. I have to look into this but I'm not sure if we can support biometrics right now because of the way biometrics work on these platforms. Having said that, we will obviously have support for biometrics in Kratos at some point!

**Comment by aeneasr** [comment]
I'm closing this because Hydra (I mistook this repo for Kratos) can not solve this issue.
