### ISSUE TITLE
Docker 

### ISSUE THREAD

**Issue by Jouda-2020** [ory/hydra#1743]
https://www.ory.sh/run-oauth2-server-open-source-api-security/

I use this site to run my own OAuth2 Server, but in step " Is it alive?" i find this error  
![image](https://user-images.githubusercontent.com/61604457/75613774-e911bb80-5b31-11ea-837d-849669fb34dd.png)

Please help

**Comment by aeneasr** [comment]
You didn’t set the DSN properly which is probably a combination of your using Windows with Bash for Git or something comparable.

**Comment by Jouda-2020** [comment]
How can i set the DSN properly, i follow the site step by step. 
can you help me to get the solution

**Comment by aeneasr** [comment]
I don’t really know what command failed for you because you did not provide any information (e.g. bash history of commands and their output), information on your operating system (I had to guess that you are using some type of bash emulator on windows). With this very limited information I am afraid that I will not be able to help you any further.

**Comment by Jouda-2020** [comment]
Can i send to you the information by email ? 
I will be thankful

**Comment by aeneasr** [comment]
No, only here.

**Comment by Jouda-2020** [comment]
![image](https://user-images.githubusercontent.com/61604457/75715523-d3d19400-5ccd-11ea-8eb6-878f6229126d.png)

![image](https://user-images.githubusercontent.com/61604457/75715568-e8ae2780-5ccd-11ea-8683-4db6f64ce99c.png)


![image](https://user-images.githubusercontent.com/61604457/75715599-f4015300-5ccd-11ea-8609-94f77dbb3e06.png)

![image](https://user-images.githubusercontent.com/61604457/75715621-fe235180-5ccd-11ea-9e0f-3dd40c6247d4.png)

![image](https://user-images.githubusercontent.com/61604457/75715642-07acb980-5cce-11ea-810a-2fd348c014b4.png)


![image](https://user-images.githubusercontent.com/61604457/75715678-18f5c600-5cce-11ea-8795-2b9fa81200d3.png)

![image](https://user-images.githubusercontent.com/61604457/75715709-24e18800-5cce-11ea-905c-3f1dd2809fff.png)

![image](https://user-images.githubusercontent.com/61604457/75715730-2dd25980-5cce-11ea-873e-0891ce2d540e.png)

![image](https://user-images.githubusercontent.com/61604457/75715750-36c32b00-5cce-11ea-892b-0c3b1f0b0dc7.png)


![image](https://user-images.githubusercontent.com/61604457/75716302-324b4200-5ccf-11ea-94aa-f7c5e072bc99.png)

**Comment by Jouda-2020** [comment]
I hope you can help me in this matter, how can i know the type of bash ? or you get it !

**Comment by aeneasr** [comment]
1. You are using `/dev/urandom` on a (mingw64) emulated bash shell. That will not work, you need to use something else like: `$ export SECRETS_SYSTEM=this_needs_to_be_the_same_always_and_also_very_$3cuR3-._`
2. Make sure you run everything in one shell, not in separate shells (windows).

Please read what environment variables are and how they work, here is a guide - you can find tons of them on google: https://medium.com/chingu/an-introduction-to-environment-variables-and-how-to-use-them-f602f66d15fa

I am going to close this issue because it does not fit the guidelines outlined for this repository. You can ask questions around environment variables and docker on sites like StackOverflow or in several chat rooms. We also have a chat room which you can find on our homepage.
