### ISSUE TITLE
No CSRF value available in the session cookie happend in the guiding demo

### ISSUE THREAD

**Issue by LuoWei0731** [ory/hydra#1751]
HI,  i install the demo follow as https://www.ory.sh/docs/hydra/5min-tutorial. the first and second time demo works welll. but after that i got 'No CSRF value available in the session cookie' error . could you help me ?

hydra_1          | time="2020-03-05T06:10:20Z" level=error msg="An error occurred" debug="No CSRF value available in the session cookie" description="The request is not allowed" error=request_forbidden hint="You are not allowed to perform this action."
![image](https://user-images.githubusercontent.com/42567149/75953238-e75a4600-5eeb-11ea-813c-f68969cbdac5.png)

**Comment by aeneasr** [comment]
Make sure to not confuse localhost and 127.0.0.1 and use a browser that allows cookies

**Comment by NicolasMahe** [comment]
I have the same issue with Chrome v84.0.4147.125.
It works with Safari v13.1.2.

I tried to change the cookie option of Chrome without any success.
Is it because of some security features of Chrome because of no HTTPs or local IP?

**Comment by ezerw** [comment]
Same here, it works fine on Safari but not on Chrome
<img width="1371" alt="Screen Shot 2020-08-13 at 5 07 45 PM" src="https://user-images.githubusercontent.com/943396/90096511-90547900-dd87-11ea-9967-a534912979b4.png">

**Comment by Tomasz-Smelcerz-SAP** [comment]
I have the same with chrome 84.0.4147.125
Hydra version 1.4.6.
Logs show this: "time="2020-08-13T11:39:28Z" level=error msg="An error occurred" debug="No CSRF value available in the session cookie" description="The request is not allowed" error=request_forbidden hint="You are not allowed to perform this action.""
It doesn't complain that CSRF token is invalid/missing, but there's no token stored in the internal Hydra session store...
It works in Firefox/Safari. Looks like this Chrome build changed something that disrupts Hydra server-side session management.

**Comment by aeneasr** [comment]
Hi there, sorry to hear that this is apparently an issue for Chrome environments.

To help, it is critical to have at least some idea of your set up. Please fill out the [issue template](https://github.com/ory/hydra/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Also note that this issue is about the 5 minute tutorial. Seeing that there are older versions reported here I assume that you're not running the tutorial.

If your environment stopped working since upgrading chrome or similar problems, please create a separate issue with **as much detail as possible.**

If you have issues with the 5 minute tutorial please state so clearly and we'll reopen this.

**Comment by aeneasr** [comment]
https://github.com/ory/hydra/issues/1988#issuecomment-673937567

**Comment by aeneasr** [comment]
https://github.com/ory/hydra/blob/master/docs/docs/debug/csrf.mdx#same-site-in-chrome
