### ISSUE TITLE
Workaround needed for CSRF SameSite=None cookies

### ISSUE THREAD

**Issue by jcxplorer** [ory/hydra#1753]
It's really good that Hydra is already supporting cookies with `SameSite=None` from https://github.com/ory/hydra/pull/1718. However, it seems like some workarounds are needed for some not-so-old browsers.

The entire issue is described here: https://auth0.com/blog/browser-behavior-changes-what-developers-need-to-know/#Working.around.incompatible.browsers

From my understanding of the workaround, when `SameSite=None` is set, a second cookie must also be set without the SameSite attribute, and both must be checked when doing the CSRF validation, as only one of them is likely to actually be available.

I think I'll have time this week to submit a PR if this sounds good.

**Comment by aeneasr** [comment]
Sounds good even though I would like to have this check configurable as some may choose not to use that feature and instead enforce strict SameSite policies :)

**Comment by jcxplorer** [comment]
I've started implementing the PR, and I've done it so that it only adds the legacy cookie if Hydra has been configured to use `SameSite=None`. I assume this is what you meant :)

I'll still write a few more tests before sending the PR, but I'm on holiday next week. I'll get back to this the week after that.

**Comment by aeneasr** [comment]
Cool!

> I've done it so that it only adds the legacy cookie if Hydra has been configured to use SameSite=None. I assume this is what you meant :)

The workaround proposed by Auth0 actually completely disables any restrictions imposed by `SameSite=None` because it always falls back to the legacy cookie which essentially disables any security measures imposed by `SameSite=None`. Therefore I think it makes sense to have an additional config key such as `enable_legacy_browser_workaround` (looking for a better name...) to explicitly dis/enable this feature.

> I'll still write a few more tests before sending the PR, but I'm on holiday next week. I'll get back to this the week after that.

Enjoy your break! :)
