### ISSUE TITLE
CLI Migration Down

### ISSUE THREAD

**Issue by aaronpcz** [ory/hydra#1763]
**Is your feature request related to a problem? Please describe.**

Currently, the CLI does not allow migrations to be reversed.

Some examples of why this might be important

1. Rolling back to a prior version, in case of breaking changes or issues in software that projects do not have ownership or ability to update.

2. Uninstalling hydra tables from a schema

**Describe the solution you'd like**

Would be great to be able to use the CLI tools with a new commend like migrate:undo.  I've had a look at the migration files and the Down statements look like they've already been written.  Just not exposed via a CLI command.

**Describe alternatives you've considered**

For example 2. this can be done manually.

[EDIT: Link from community.ory.sh](https://community.ory.sh/t/hydra-migrate-cli-undo-migration/1557/3)

**Comment by harsimranmaan** [comment]
While this would certainly be useful for dev or test workflow, running this on a prod db could be catastrophic as it could lead to data loss. I remember explicitly disabling `rake db:rollback` for prod env in the past to avoid this scenario. Maybe a bit more context would help plan the migrate:down better. For 1, it is also useful in ensuring backwards compatibility for  the database schema so that schema rollbacks are not desired. Schema alteration become very expensive as the DB size grows on certain Db engines(looking at you Mysql).

**Comment by aeneasr** [comment]
Yeah I agree, there will certainly be data loss.
