### ISSUE TITLE
OAuth2 Token Revocation

### ISSUE THREAD

**Issue by NavindrenBaskaran** [ory/hydra#1765]
Hey apologies this is a random question.

I will really want to understand why do we need to perform Authorization Basic (client credentials) authentication when we are revoking an access token. Why can’t we use Authorization Bearer authentication?

Existing OAuth token revocation endpoints include Basic authentication (client credentials) and place the access token to be acted upon in the request body, why can’t we just use Bearer authentication which places the access token in the header. Then the authorization server after authentication revokes the token placed in the header.

**Comment by aeneasr** [comment]
Because that's how it's defined: https://tools.ietf.org/html/rfc7009#section-2.1

**Comment by NavindrenBaskaran** [comment]
Yes, you are right I get that. But I will want to understands why is that the case. Are we using client credentials here because only token revocation is only limited to oauth clients and not to the users?

**Comment by aeneasr** [comment]
Please refer that question to the IETF, we're just following spec!

**Comment by NavindrenBaskaran** [comment]
Okay thank you @aeneasr.

**Comment by t2wu** [comment]
@aeneasr Just like to point out that the purpose of the HTTP Basic authentication is to verify the client, so that client is permitted to perform the revocation. And the token to be revoked is placed inside HTTP body, probably because the token to be revoked is a payload, not a mean to authenticate the client or the user itself.
