### ISSUE TITLE
docs: Incorrect/misleading description of fallback URLs

### ISSUE THREAD

**Issue by dalcde** [ory/hydra#1931]
The documentation for `urls.{login,consent,logout}` say "Defaults to an internal fallback URL", but in reality the server returns an error when these are not set: https://www.ory.sh/hydra/docs/reference/configuration

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.

**Comment by dalcde** [comment]
[Here](https://github.com/ory/hydra/blob/master/oauth2/handler.go#L85) the fallback for a missing LoginURL is set to an empty page raising an `InternalServerError`, which is not what one would expect when the documentation says "defaults to an internal fallback URL"
