### ISSUE TITLE
Postgresql Migrate SSL required

### ISSUE THREAD

**Issue by saul-gush** [ory/hydra#1942]
I cant seem to get my managed Digitalocean postgresql database to connect

time="2020-07-04T17:29:16Z" level=error msg="Unable to ping SQL database backend" dsn="postgres://*:*@xxx.db.ondigitalocean.com:5432/auth?ssl=true&sslmode=require" error="failed to connect to `host=xxx.db.ondigitalocean.com user=doadmin database=auth`: server error (FATAL: parameter \"ssl\" cannot be changed now (SQLSTATE 55P02))"

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.
