### ISSUE TITLE
"debug" log level outputs multiline logs

### ISSUE THREAD

**Issue by Guyzeroth** [ory/hydra#1958]
**Describe the bug**

Setting LOG_LEVEL to "debug" outputs JSON logs out on multiline. 

**Reproducing the bug**

Set log level to debug and observe new lines in multi-line logging

**Expected behavior**

No multiline logging - as with "info" log level. 

**Environment**

oryd/hydra:v1.5

**Additional context**

This is more of an annoyance as it logs out many many lines for a debug log configuration making issues harder to piece together (and breaking our JSON field mappings in elasticsearch)

**Comment by aeneasr** [comment]
The idea behind this was that `debug` logging is prettified to help operators read the logs. I found it very hard to read JSON logs when debugging because of the one-liner.

What does this break in elasticsearch?

**Comment by aeneasr** [comment]
Workaround is of course to set log level to info :)

**Comment by harsimranmaan** [comment]
I also find it hard to debug one-line json. maybe check the log forwarder(if you are using one) config to see if it can support multiline json. ES supports multiline json blocks

**Comment by skymeyer** [comment]
Although I understand the idea behind it, this prevents us from running debug mode with `json` format properly in for example Kubernetes environments on dev environments. This is probably also related to the breakage @Guyzeroth is experiencing as this relates to any log ingestion system.

Assuming that debug is only used when an operator is behind the output is not a correct assumption in my opinion. I strongly believe the "workaround" should be to change the format to `text` to have better readability rather than having an inconsistent log output format depending on the `level`.

**Comment by aeneasr** [comment]
I understand, in fact I was thinking about moving this explicitly to the output format. So instead of the current behavior:

* `text`: text format
* `json`: json format
* `json_pretty`: json human readable format

That way the log output is not dependent on the level, but on the ... output. Should have done that from the beginning ;)

**Comment by aeneasr** [comment]
If anyone is interested on picking this up, the relevant lines are here: https://github.com/ory/x/blob/master/logrusx/logrus.go#L37-L40

If you do, please add a test :)

**Comment by Guyzeroth** [comment]
Thanks for the feedback guys. We did indeed set it to "info" as a work around.

**Comment by aeneasr** [comment]
Merged on master
