### ISSUE TITLE
PK column auto increment causing issues

### ISSUE THREAD

**Issue by prathik-kaliyambath** [ory/hydra#1991]
**Describe the bug**
I'm unsure whether this is a bug necessarily, but hydra exhibits a weird behaviour while adding clients and the sequence of pk has been distorted.

**Reproducing the bug**

Add a few clients, mess up the pk ordering by deleting N clients in between or in the start, try adding N + 1 clients (or more) after that, the N + 1th client and onwards the /clients POST API gives a 409 conflict on the request.

**Expected behavior**

POST requests not giving 409 when adding a new client with a unique client_id, irrespective of what's going on with the pk column.

**Environment**

- Version: v1.4.2 // but i guess its not really version dependent.

**Additional context**
Why not just use the max(pk) and add 1 to that each time a client is added? Won't that be a simpler logic, and potentially have a lesser scope for collisions/ bugs?

**Comment by aeneasr** [comment]
Database?

**Comment by prathik-kaliyambath** [comment]
PostgreSQL running on AWS RDS.

**Comment by aeneasr** [comment]
`pk` is a `SERIAL` (https://github.com/ory/hydra/blob/master/internal/fizzmigrate/client/migrations/sql/postgres/9.sql#L3) so this is nothing that should/could be fixed on ORY Hydra's side in my opinion. Not sure how you are deleting clients but generally this shouldn't be an issue.

If you used sharded databases or other HA set ups, that could be the issue - please check the PostgreSQL documentation around that (and if you want report here if others have the same issue :) )

**Comment by prathik-kaliyambath** [comment]
Yes I did check this part of the code earlier and also the createClient portion in helpers.js, even I wasn't sure if much could be done at hydra's end.
We aren't using a sharded set up as such, just a normal RDS instance. 
Clients were deleted using the DELETE request.

One possible suggestion that could be added on hydra with a future release would be to have a check before inserting, and not give a conflict response if it's due to pk, instead just use the max(pk) + 1.

**Comment by aeneasr** [comment]
PostgreSQL ensures that SERIAL can not cause CONFLICTS so I'm a bit stunned how that would even be possible, `max(pk)+1` is what `SERIAL` does. If you get a 409 conflict, I suspect that it's because of a duplicate client ID instead, or because of a failed DELETE attempt.

**Comment by prathik-kaliyambath** [comment]
Haha i thought that was the case too (ie conflicting client_ids) , but I have confirmed that it isn't the cause by checking inside the DB and also tried inserting with long strings with gibberish alphabets just to ensure the same. Even I wasn't able to pin point the issue to a cause as such.
I am not very sure how PosgreSQL internally implements the Auto Increment, but a theory I had is that they could be picking the next value based on insert time and not the max value(pk) itself, this might be causing the issue, if the pk and created_at doesn't have the same ordering.

**Comment by prathik-kaliyambath** [comment]
Since, when I insert to a db with 150 entries, and say a gap from 1-12, the new client being created has a pk of 1 and not 151, if that makes sense.

**Comment by aeneasr** [comment]
For serial, check out https://www.postgresqltutorial.com/postgresql-serial/ which also includes guidance on getting the current SERIAL offset.

We have quite a few integration tests that include deletion and creation of clients against a PG database and have never observed these issues and also never received any bug report regarding this. Given how `SERIAL` works I again can only say that I don't see how this could happen.

Regarding `max(pk)+1` the problem is that we can't use indices which makes lookup quite slow. Given that we use SERIAL everywhere, it would be required to use this approach elsewhere too where there are much more rows, leading to very bad performance.

In general, `SERIAL` takes care of this automatically, unless something in the PG database is broken or whatever. If you have a reproducible case, that would also help narrow the bug down because from my current perspective I can absolutely not see how this can happen / be related to SERIAL.

**Comment by prathik-kaliyambath** [comment]
Looks like it was an issue in the Auto Increment last value at our db. It somehow got reset to a count smaller than the max value, possibly due to some updates that were done.
Thank you for your quick response.
