### ISSUE TITLE
Issue while using SERVE_TLS_ALLOW_TERMINATION_FROM

### ISSUE THREAD

**Issue by ysaakpr** [ory/hydra#1998]
**Describe the bug**
I have a typical Kubernetes setup as shown below, I can call the hydra APIs while configured `SERVE_TLS_ALLOW_TERMINATION_FROM` externally through the LB and the API gateway. But within the cluster, which I trust, I am unable to call the hydra APIs directly using Kubernetes service.
![hydratls](https://user-images.githubusercontent.com/20730186/90482888-8947b500-e151-11ea-87df-23ec678fe575.jpg)

In the above image, https calls through LB works. But direct calls from a service1 to hydra is failing. Is there a way to accept this calls without X-Forwarded-Proto?

**Comment by vinckr** [comment]
Hey ysaakpr, 
Thanks for reporting this. 
Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.
> Do not edit the original post as we will not be notified when you do so.

Thanks for your time!

**Comment by IonFoXx** [comment]
Hi,

apparently I need to say that we ran into the very same issue as you. The solution we been coming up with was to set the X-Forwarded-Proto header manually.

The setup we have is with an Istio service mesh and mTLS between all services, which means all traffic is encrypted at all times. So we have setup a VirtualService (istio specific) for cluster internal traffic which matches the host header hydra.default.svc.cluster.local and only than adds the X-Forwarded-Proto header.
To prevent spoofed host header requests from public sources, we only allow traffic, with a correct host header set to the public domain name (eg. hydra.example.com) into our cluster. So you can't send a request to the public ELB IP Address with the host header set to hydra.default.svc.cluster.local. Public traffic with the wrong host header will get declined at the edge. There is still the danger of a compromised service within the cluster.

I don't recommend you to go the Istio service mesh route as it is a lot to learn but maybe you can trust your internal traffic as we and set the header manually.

I think it would be really hard to implement a "fix" for this issue within hydra because hydra would need to know everything about your network topology and which traffic to trust. Especially in an always changing environment like a Kubernetes cluster. 

I hope it helps a little and maybe someone has a better idea!?

**Comment by aeneasr** [comment]
Hi there, we will be addressing this with #1962 - is it ok if I close this as a dupe?
