### ISSUE TITLE
Multi-region deployment support

### ISSUE THREAD

**Issue by FredrikAppelros** [ory/hydra#2018]
**Is your feature request related to a problem? Please describe.**

Trying to deploy Hydra in multiple geographically distant regions where there is a significant amount of data replication lag can be challenging. In this scenario, it is desirable to be able to control the data consistency in a more granular fashion than what Hydra currently supports. On one hand, you want your data to be global so that it can be used at any of the regional endpoints. But on the other hand, there are use cases where you cannot accept the resulting latency of a global data replication scheme.

However, there is one realization that makes it possible to reconcile these two principles. The requirements for interacting with clients versus tokens are usually completely different.

You want your client data to be globally replicated so that they can be used across all regions. However, modifications to clients are usually not very latency-sensitive. Having an eventual data consistency model for clients is usually acceptable. The same does not hold true for tokens though.

Tokens are very latency-sensitive and should be valid as soon as they are returned. On the other hand, there is usually no need for tokens to be replicated across regions. Most use cases for tokens operate within one region where it is both issued and used.

Hence, there is room for allowing this flexibility to be used to our advantage, by allowing different replication and data consistency models to be applied to clients versus tokens. Now Hydra does not make this easy if you opt for using a traditional RDBMS for storage since they typically do not let you configure this on a per-table basis, but only on a per-database basis. To support this Hydra would have to allow the client data to go into its datastore separate from the token data.

**Describe the solution you'd like**

It would be great if Hydra added support for either splitting the client and token data sources or figure out another way to support multi-region deployments, potentially by supporting some kind of NoSQL datastore which allows for this type of flexibility.

**Describe alternatives you've considered**

One suboptimal solution which does not require any modifications to Hydra itself is to use a SQL-aware proxy such as ProxySQL in front of the database that Hydra uses. You can then configure it so that queries directed at certain tables end up in a different database instance. This way you achieve the split on a per-table basis.

The issue with this is that it requires additional modifications to the database schema to remove the foreign key constraints on the token-related tables as they can no longer refer to the `hydra_client` table anymore. Since this also implies that cascading deletes would no longer work, there would also be additional work needed to add cleanup jobs to ensure that there are no dangling records when a client is removed.

**Comment by aeneasr** [comment]
Thank you for the great write up, here are some thoughts!

> Tokens are very latency-sensitive and should be valid as soon as they are returned. On the other hand, there is usually no need for tokens to be replicated across regions. Most use cases for tokens operate within one region where it is both issued and used.

I agree, tokens are latency-sensitive operations that should be available almost immediately in a specific region. I think it is ok if there is some replication lag for other regions, but they should eventually end up there as well within a 1 second (complete guess) timeframe to make the system globally available.

> Hence, there is room for allowing this flexibility to be used to our advantage, by allowing different replication and data consistency models to be applied to clients versus tokens. Now Hydra does not make this easy if you opt for using a traditional RDBMS for storage since they typically do not let you configure this on a per-table basis, but only on a per-database basis. To support this Hydra would have to allow the client data to go into its datastore separate from the token data.

I think that traditional RDBMS like MySQL and PostgreSQL definitely to not fit the task. Commercial adaptations such as AWS Aurora (as you pointed out :) ) do have concepts for replication using block storage but the replication level is usually database-wide.

Generally I think that traditional RDBMS do not solve this because they are not designed to. There are workarounds such as the AWS model but there will always be limitations.

> It would be great if Hydra added support for either splitting the client and token data sources or figure out another way to support multi-region deployments, potentially by supporting some kind of NoSQL datastore which allows for this type of flexibility.

Honestly, I think that if we put the effort into implementing multi-region support, we should aim for implementing it in such a way that it works really, really well with an underlying technology that has planet-scale deployments at it's core, such as AWS Dynamo DB, Google Cloud Spanner, Google BigTable (to name the commercial products) or Apache Cassandra, CockroachDB (to name the open-source ones, there might be more of course).

To make a decision on which one to support I think it would be good to be aware of limitations in support, deployment, scalability, and so on - and then pick a technology that works best for the majority of the users. In general, I am not a fan of going down the cloud vendor path because it locks you into a specific ecosystem which the antagonist of free software. Also, I do not like the business practices of AWS specifically with regards to Aurora.

Personally, I really like the CockroachDB project. It removes the need for an additional search engine (which e.g. DymanoDB needs) and does a lot of optimizations on the schema - plus - it's compatible with most SQL and definitely already compatible with ORY Hydra because people use it in production already.

I know that it's a new company, with a new business, and a lot of unsolved issues. And I do understand that it's years before most people will accept the risk to use it as the database of their choice, but I love their engineering, openness, and approach to distributed databases which doesn't suck.

Anyways, let's explore some of the alternatives. I'm super open to just learn about this space because I personally have never deployed a single Apache Cassandra instance, nor used DynamoDB anywhere!

**Comment by ericot** [comment]
I've done some initial research on how CockroachDB can be used to implement the consistency model described by @FredrikAppelros.

CockroachDB provides several features to support geo-partitioned data such as [replication zones](https://www.cockroachlabs.com/docs/v20.1/configure-replication-zones), [table partitioning](https://www.cockroachlabs.com/docs/v20.1/partitioning) and [locality](https://www.cockroachlabs.com/docs/v20.1/cockroach-start#locality) of nodes in the cluster. However, these are **enterprise** features which limits their availability.

The implementation of geo-partitioning with CockroachDB relies on defining some data (columns) that can be used to specify the _locality_ of table rows. This information is then used to distribute the _ranges_ of data and dictates which node becomes the _leaseholder_.

How to handle locality for entities in Hydra (clients, tokens etc.) is an interesting subject. One simple solution is to add the information as metadata associated with the relevant entities/tables and expose them in the API. I.e. tokens could be assigned a locality when created, while clients do not make any distinction as to where they are created.

I've not looked into alternative solutions for geo-partitioning but It would be interesting to see how other implementations handle distribution and replication. Maybe there are some common concepts, such as locality, which can be distilled into a generic implementation that could make multi-regional deployments simpler.

**Comment by aeneasr** [comment]
Nice, thank you for the summary!

**Comment by exilitco** [comment]
Actually DynamoDb only needs a search engine if you do text search. "relational" schema and normal CRUD operations (with or without transactions) is a perfect match.  In combination with possibility of running hydra as a lambda function would be a dream.

Regarding geo-sharding etc, I believe this should be handled by hydra and never by the backing data store. E.g revoking should still work in any region despite a specific region being temporary down. Master/slave/replication/load balancing/failover is IMHO critical application logic and should not be outsourced to the data store. Perhaps multi-regional deployments could be handled like separate installations with no shared resources other then hydra<->hydra communication and request redirection in between. That would simplify potential upgrades and make it more resilient.

**Comment by aeneasr** [comment]
Just wanted to let you know that we plan on going with CockroachDB as the multi-region database solution in our cloud service. We do not plan on supporting any other key/value stores or other databases. This might change at some point if we find out that CRDB does not perform as expected.

Thank you for all of your input - closing this in the meanwhile as CRDB is already supported.

**Comment by winterheart** [comment]
Hi. CockroachDB recently changed license from permissive Apache 2.0 License to more restrictive Business Source License, that can be serous obstacle to future users of Ory. Have you reviewed other solutions like Cassandra/Scylla? 
As I see, most of features of commercial CRDB supports by Open Source Cassandra, like geo-replication and sharding. Data replicates between data-centers as is, without additional maintenance, and overall Cassandra cluster behaves as cloud database, you don't have to know whole topology, only entry point and optional DC awareness.

**Comment by aeneasr** [comment]
Apache Cassandra is not wire-compatible with any established SQL dialect such as MySQL or PostgreSQL. Therefore it is extremely unlikely for this to ever be considered as it is too much effort and there are new databases with wire-compatibility spawning by the month.

On a side note, CRDB has a process to convert BSL to APL-2.0, so you can still use CRDB with APL-2.0 license, you just can't use the most recent versions under that license: https://www.cockroachlabs.com/docs/stable/licensing-faqs.html
