### ISSUE TITLE
Logout problem

### ISSUE THREAD

**Issue by kientv** [ory/hydra#2050]
I'm using hydra 
and already whitelisted `post_logout_redirect_uri`. but i always see error as below:

`The OAuth2 request resulted in an error.
Error: invalid_request
Description: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed
Hint: Logout failed because query parameter post_logout_redirect_uri is not a whitelisted as a post_logout_redirect_uri for the client
Debug:
You are seeing this page because configuration key urls.error is not set.`

**Comment by kientv** [comment]
My logout uri like this:

/oauth2/sessions/logout?id_token_hint=`id_token`&post_logout_redirect_uri=http%3A%2F%2F127.0.0.1%3Fstate%3Dbf2f4b1a44e8d963b782d69915e1b861b11972c765e7b06051546a13"
`

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.
