### ISSUE TITLE
[Question] Create Client fails using example

### ISSUE THREAD

**Issue by DarkBlaez** [ory/hydra#2060]
I am running the example but using v1.7.4 and minor change in the naming of the container. The container responds with a status:ok so I know it is reachable and operational. When I try to create a client with this:

docker run --rm -it \
  --network hydraguide \
  oryd/hydra:v1.7.4 \
  clients create \
    --endpoint http://oryhydra:4445 \
    --id some-consumer \
    --secret some-secret \
    --grant-types client_credentials \
    --response-types token,code

I get this error:
Config file not found because "Config File ".hydra" Not Found in "[/]""
You should not provide secrets using command line flags, the secret might leak to bash history and similar systems
Unable to connect to "http://oryhydra:4445/clients", unexpected HTTP error status code: 500\nUnable to connect: http: ContentLength=286 with Body length 0
Unable to connect: http: ContentLength=286 with Body length 0
Unable to connect: http: ContentLength=286 with Body length 0
Unable to connect: http: ContentLength=286 with Body length 0

Please advise, this has been racking my brain for a bit

Thanks
DB

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.
