### ISSUE TITLE
CockroachDB high CPU on cascade deletes

### ISSUE THREAD

**Issue by purmac** [ory/hydra#2133]
**Environment**
- Version: v1.7
- Database: CockroachDB

**Describe the bug**
When calling the client delete api, Hydra submit the SQL command `DELETE from hydra_client where id = <client_id>`. Since there is a foreign key cascade delete constrain on `hydra_oauth2_access` table. If there are many records for that client id in `hydra_oatuh2_access` table (in our case around 50k), the database will take significant amount of time to finish this operation and cause Hydra to timeout. We observed high CPU usage and eventually CPU saturated in our database cluster.

I was wondering if Hydra can implement a transaction that includes batch delete from large table such as `hydra_oauth2_access`. Or a more aggressive clean up job to keep token size in a manageable range.

**Comment by aeneasr** [comment]
Hey there, thank you for the report. CRDB is currently a second-class citizen support and while cascade deletes can in fact become slow with many rows, it shouldn't completely hang the database. Therefore I'd like to you to forward the question to the CRDB team and see what ideas they have around optimization. This might also depend on the CRDB version you're using. If they have some ideas how to improve this in SQL-land we can take another look. Otherwise we'll just be poking around in the dark, putting work into things that work well for other databases and that could be solved otherwise (e.g. with some CRDB config).

**Comment by aeneasr** [comment]
Given the lack of input from the author, I am closing this.
