### ISSUE TITLE
No CSRF value available in the session cookie

### ISSUE THREAD

**Issue by misha-234927** [ory/hydra#2345]
0.	I am trying to set up a sample configuration as described in the ORY Hydra 5 Minute Tutorial using ORY Hydra v1.9.2 (binary distribution «hydra_1.9.2_windows_64bit.zip» installed locally on Windows 6.1 (7 SP1).

1.	I run the Hydra server as follows:
```
@SET SECRETS_SYSTEM=this_needs_to_be_the_same_always_and_also_very_$3cuR3-._
@SET DSN=postgres://hydra:secret@localhost:5432/hydra?sslmode=disable
@SET LOG_LEAK_SENSITIVE_VALUES=true
@SET URLS_LOGIN=http://127.0.0.1:9096/login
@SET URLS_CONSENT=http://127.0.0.1:9096/consent
hydra serve all --dangerous-force-http
```

2.	I create a test client as follows:
```
@SET HYDRA_ADMIN_URL=http://127.0.0.1:4445/
hydra clients create --id consumer2 --secret secret --scope openid,offline --callbacks http://127.0.0.1:4446/callback
```

3.	I run the user login and consent example app (hydra-login-consent-node) as follows:
```
@SET HYDRA_ADMIN_URL=http://127.0.0.1:4445/
@SET PORT=9096
npm start
```

4.	I initialize an OAuth2 authorize code flow as follows:
```
@SET OAUTH2_CLIENT_ID=consumer2
@SET OAUTH2_CLIENT_SECRET=secret
@SET HYDRA_URL=http://127.0.0.1:4444
hydra token user
```

5.	OAuth2 authorize code flow breaks at the login stage with the following error (see image below): 

> message:request_forbidden reason: No CSRF value available in the session cookie. status:Forbidden status_code:403

Tested with Google Chrome 87.0.4280.141 and Mozilla Firefox 85.0.1.

![1](https://user-images.githubusercontent.com/78696665/107154979-a7bb9a00-6997-11eb-98db-ba61f60b4f13.png)

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.
