### ISSUE TITLE
userinfo endpoint returns fields even when openid scope was not granted/requested

### ISSUE THREAD

**Issue by mitar** [ory/hydra#2456]
**Describe the bug**

I am looking at the userinfo endpoint in Hydra and from my testing it looks like it is returning fields even when there is no ID token associated with the access token, e.g., the `openid` scope was not granted/requested in the first place.

I tried to understand what the spec says in this case, but I could not find anything relevant. In any case, I think it should or return an error or return an empty `{}` object, and not some fields.

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.

**Comment by mitar** [comment]
What I am saying is that an access token without `openid` scope should fail. I see few examples of such checks in other implementations, where access token for userinfo endpoint is required to have `openid` scope otherwise it fails:
* https://github.com/juanifioren/django-oidc-provider/blob/master/oidc_provider/views.py#L223
* https://github.com/gravitee-io/graviteeio-access-management/blob/de9e5a4cc61d64fa58e51223d2ece72f9e4b2660/gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/OIDCProvider.java#L174
* https://github.com/IdentityServer/IdentityServer4/blob/3ff3b46698f48f164ab1b54d124125d63439f9d0/src/IdentityServer4/src/Validation/Default/UserInfoRequestValidator.cs#L49-L52
  * See also tests: https://github.com/IdentityServer/IdentityServer4/blob/3ff3b46698f48f164ab1b54d124125d63439f9d0/src/IdentityServer4/test/IdentityServer.IntegrationTests/Clients/UserInfoClient.cs#L98-L145

So it looks other implementations return `insufficient_scope` error if access token used to access userinfo endpoint does not include `openid` scope. That would address my concerns in this issue.

I do admit that I have not found relevant description of this behavior in the spec, though. But it makes sense to me.

**Comment by aeneasr** [comment]
In that case this is a wontfix as it introduces a significant breaking change with little upside and no guidance from the OIDC Foundation or other security reasoning. To me, the OIDC guidance is clear ins saying that a „sub“ field shall always be returned and it is also what I have seen in public implementations from Google and others.

**Comment by mitar** [comment]
So I used https://developers.google.com/oauthplayground/ and Google is doing some funky stuff. If I enter only `email` as scope in the field and click `Authorize APIs`, after exchanging code for tokens, I get an access token with the following scope: `"scope": "https://www.googleapis.com/auth/userinfo.email openid". As you see, `openid` was automatically added even if it was not in the request. And yes, then doing request against `https://openidconnect.googleapis.com/v1/userinfo` returns a response.

After that I made an access token only with `https://www.googleapis.com/auth/documents` scope. So no `email` and no `openid`. I got back access token only with `https://www.googleapis.com/auth/documents` scope. Now, making a request to `https://openidconnect.googleapis.com/v1/userinfo` with such access token (no `openid` scope) gives me:

```
{
  "error_description": "Invalid Credentials", 
  "error": "invalid_request"
}
```

So, I think my statement still holds. If there is no `openid` scope in the access token, userinfo endpoint should fail. You mentioned that Google always returns `sub`, but this is not true, it fails it. I have also made links above to other open source implementations which also fail userinfo requests with access tokens without `openid` scope

So I would ask that this is reopened and that userinfo fails if the access token provided does not contain `openid` scope.

**Comment by aeneasr** [comment]
My comment was false then, sorry about that.

It still doesn't make sense to break the 30.000+ existing installations of Ory Hydra and all their downstream applications (presumably in the millions) to satisfy something which is not required by the specification or the certification process.

This is a nofix from my side because the disadvantages are so, so much more than the advantages of implementing this.

**Comment by mitar** [comment]
Why do you think this would break things for anyone? What is the use case where current behavior is an expected one?

**Comment by mitar** [comment]
I would claim that this is a privacy problem. Using an opaque access token (when not using JWT) I am now able to obtain subject ID, even when I should not be (user has not given consent to that).

**Comment by aeneasr** [comment]
It breaks for everyone relying on `userinfo` working without the `openid` claim.

**Comment by mitar** [comment]
Anyway, I think we can leave it closed and see if anyone else complains about this at any point in the future.
