### ISSUE TITLE
Invalid TLS config after upgrading to 1.10.2

### ISSUE THREAD

**Issue by jbub** [ory/hydra#2518]
**Describe the bug**

I was running 1.10.1 with no problems with the following env var:

```
SERVE_TLS_ALLOW_TERMINATION_FROM: "172.17.0.0/16,172.18.0.0/16,172.19.0.0/16,172.20.0.0/16,172.21.0.0/16,172.22.0.0/16,172.23.0.0/16"
```

After running 1.10.2 with updated setup:

```
SERVE_ADMIN_TLS_ALLOW_TERMINATION_FROM: "172.17.0.0/16,172.18.0.0/16,172.19.0.0/16,172.20.0.0/16,172.21.0.0/16,172.22.0.0/16,172.23.0.0/16"
SERVE_PUBLIC_TLS_ALLOW_TERMINATION_FROM: "172.17.0.0/16,172.18.0.0/16,172.19.0.0/16,172.20.0.0/16,172.21.0.0/16,172.22.0.0/16,172.23.0.0/16"
```

I am getting "The configuration contains values or keys which are invalid"

Probably related to https://github.com/ory/hydra/pull/2476.

**Reproducing the bug**

Run application with provided env vars on version 1.10.2.

_Server logs_

```
The configuration contains values or keys which are invalid:
serve.public.tls: map[allow_termination_from:172.17.0.0/16,172.18.0.0/16,172.19.0.0/16,172.20.0.0/16,172.21.0.0/16,172.22.0.0/16,172.23.0.0/16]
                  ^-- doesn't validate with "#/definitions/tls_config"

The configuration contains values or keys which are invalid:
serve.public.tls.allow_termination_from: 172.17.0.0/16,172.18.0.0/16,172.19.0.0/16,172.20.0.0/16,172.21.0.0/16,172.22.0.0/16,172.23.0.0/16
                                         ^-- expected array, but got string
```

_Server configuration_

Env vars as posted above.

**Expected behavior**

Application boots without any problems.

**Environment**

- Version: v1.10.2
- Environment: Docker

**Comment by aeneasr** [comment]
Thank you for the report - does the original configuration still work though?

**Comment by jbub** [comment]
> Thank you for the report - does the original configuration still work though?

It does not, crashes with:

```
time=2021-05-04T18:11:05Z level=fatal msg=Unable to instantiate configuration. audience=application error=map[message:I[#/serve/tls] S[#/properties/serve/properties/tls/$ref] doesn't validate with "#/definitions/tls_config"
  I[#/serve/tls/allow_termination_from] S[#/definitions/tls_config/properties/allow_termination_from/type] expected array, but got string] service_name=ORY Hydra service_version=v1.10.2
```

If i remove `SERVE_TLS_ALLOW_TERMINATION_FROM`, the application boots.

**Comment by aeneasr** [comment]
Does setting this in YAML / hydra config instead work? So is just env var broken?

**Comment by jbub** [comment]
Hmm i never used yaml config, only env vars, so possibly its only related to env vars.

**Comment by svrakitin** [comment]
We are currently running it in production with YAML config. I actually never checked that it works with env vars. I wonder how did it pass schema checks before as it is using same `Strings/StringsF` accessors.

**Comment by aeneasr** [comment]
My suspicion is that we are not properly resolving the `$ref` indirection. Before we had no `$ref` for cidr, now we have one `$ref` to `tls_config` and then one more to `cidr`.  This most likely causes the paths returned by [`ListPaths`](https://github.com/ory/x/blob/master/configx/koanf_env.go#L21) to not have the correct type [`StringSlice`](https://github.com/ory/x/blob/master/configx/koanf_env.go#L53) which leads this code to just use the [type it is given](https://github.com/ory/x/blob/master/configx/koanf_env.go#L71) - which is a string.

However, the code should actually follow [those refs](https://github.com/ory/x/blob/c44ebcb2122240a8a98f26e1664f5ad3f7bd49f7/jsonschemax/keys.go#L301). I guess we would need to add a [failing test case](https://github.com/ory/x/blob/c44ebcb2122240a8a98f26e1664f5ad3f7bd49f7/jsonschemax/keys_test.go) using the new Ory Hydra config schema to see if it is indeed caused by this.

If it is not, the problem probably lies in the [env provider](https://github.com/ory/x/blob/master/configx/koanf_env.go).

If one of you has time to pick this up, I would be super grateful!

**Comment by aeneasr** [comment]
For people having this issue a workaround is to define this config item in the YAML / JSON config file instead of as an env var!

**Comment by svrakitin** [comment]
@aeneasr I am looking into this right now. My bad here.

**Comment by aeneasr** [comment]
Thank you! All good, I think this might be a complex bug in the config parsing mechanism.

**Comment by svrakitin** [comment]
It seems like we just need to start following `$ref`s in `items` here: https://github.com/ory/x/blob/c44ebcb2122240a8a98f26e1664f5ad3f7bd49f7/jsonschemax/keys.go#L225.

**Comment by svrakitin** [comment]
I guess this should work after bumping `ory/x` to `v0.0.233`
