### ISSUE TITLE
JWK: improve key rotation 

### ISSUE THREAD

**Issue by seremenko-wish** [ory/hydra#2535]
**Is your feature request related to a problem? Please describe.**

By using a new/fresh key for signing access or ID tokens, Hydra leaves no choice to clients and forces them to hit Hydra's endpoint every time they see an unknown key. So sending multiple requests with invalid `kid`s to one of the clients could init DDOS attack on the Hydra server.

For reference, Hydra key rotation documentation: https://www.ory.sh/hydra/docs/guides/secrets-key-rotation/#rotation-of-json-web-token-signing-keys

**Describe the solution you'd like**

Introducing a configurable delay for using a fresh key for signing tokens would provide an opportunity for clients to prepare for receiving JWTs signed by a new `kid`, and rely only on periodic JWK updates not caused by user agents.

**Describe alternatives you've considered**

Distributing JWKS files by CDN would be helpful, but not reliable as requests with new `kid` might come earlier than all CDN edge nodes could be updated.

**Additional context**
Auth0 response to this problem: https://community.auth0.com/t/caching-jwks-signing-key/17654/2

**Comment by aeneasr** [comment]
Thank you @seremenko-wish for the issue. Since `/.well-known/jwks.json` is public knowledge and requires no authorization the attack surface for a DDoS would be, in my opinion, one of launching a direct attack against that endpoint at Ory Hydra using e.g. 10 servers with `hey`.

Immediate revokation of cryptographic keys is, I believe, quite important. What we could do to optimize throughput might be to add a tiny cache in Ory Hydra for the well known key so that the database is not increasing in QPS when that happens. This would definitely be much easier to implement than a grace period! :)

What do you think?

**Comment by seremenko-wish** [comment]
Key revocation is straightforward removing keys from DB. So if we implement a delayed private key utilization, that should not impact existing functionality.

**Comment by seremenko-wish** [comment]
Yeah, we approach this problem from different angles :) Your scenario is more complicated than it could be. Malice does not need to trick anybody to send anything. An attacker can just send requests directly to an API endpoint that expects the JWT token as a parameter. So the schema is Attacker ---> (API Gateway) ---> API ---> Hydra. So all requests from Attacker will end up in Hydra endpoint that returns static content.

Back to your points:
1) you don't need to generate a valid JWT token. It is enough to take a header part of JWT, base64-decode it, change `kid` in JSON, and base64-encode it back. Signature and payload do not matter here.
2) yes, it is possible, and it needs a separate solution: internal caching, rate limiting, etc.
3) True, but it will allow API Gateways or APIs to reject invalid tokens very fast and as scale on their own, without hitting Hydra on every request. 

> Adding a grace period to Ory Hydra's endpoint would only help clients which respect that grace period.

It does not matter if the client respects the grace period or not, it will start receiving JWT tokens signed with a new key set after X minutes. It is a client's choice whether it wants to use that time for caching or skip caching whatsoever (and hit Hydra JWKS endpoint).

**Comment by aeneasr** [comment]
I’m still not clear if I understand the scenario. Why could Malice not just call the well-known endpoint herself? It is a publicly exposed endpoint and there is little reason to trick some OAuth2 clients into making unnecessary requests to the endpoint. It is easier to mount an attack directly against a publicly available endpoint than going through an indirection. Maybe you are not exposing that endpoint publicly which is why you worry about this? However, from OAuth perspective, this endpoint is always exposed directly on the public internet so a protection i. that endpoint (e.g. a JWK cache) would be very much preferable than mechanisms that trust the OAuth2  clients to behave in a certain way - as OAuth2 clienrs can generally not be trusted. The JWKS endpoint is generally also used for OpenID Connect verification which MUST be public!

**Comment by seremenko-wish** [comment]
Let's return to this conversation later. I think I can handle this by introducing cache in CDN and triggering cache invalidation alongside key rotation
