### ISSUE TITLE
Ory Hydra generating code for grant_type:authorization_code for invalid aud

### ISSUE THREAD

**Issue by ejazkhan172** [ory/hydra#2539]
on  hydra_1.10.2_linux_64bit i'm facing issues as 
**Ory Hydra generating code for grant_type:authorization_code if invalid audience is provided  on request.**
As per my knowledge of oauth2 , if audience is not from the ones which are provided in  "audience":["string"]  client  during client create api, **it should not generate auth code**.

**Os : ubuntu 16
hydra : hydra_1.10.2_linux_64bit**

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.
