### ISSUE TITLE
Indicate _which_ request generates the error "The request failed with the following error message:"...

### ISSUE THREAD

**Issue by mcandre** [ory/hydra#2643]
**Is your feature request related to a problem? Please describe.**

There is very little context to debug the error message `The request failed with the following error message:`...

**Describe the solution you'd like**

Please note the basic *HTTP request URL* that triggers the error, so that engineers are better positioned to investigate errors.

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment.

If you have used an issue template and see this comment, it means that your description lacks information that allows maintainers to understand what problem you are facing and how to reproduce it.

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed. Thank you for your understanding!
