### ISSUE TITLE
Client Authentication fails

### ISSUE THREAD

**Issue by aravindc26** [ory/hydra#2907]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hydra does not allow client authentication even though the client id and secret is correctly sent.

### Reproducing the bug

curl --location --request POST 'https://localhost:9000/oauth2/token' \
--header 'Authorization: Basic NjA0ZDE4NzYtMzkyOS00OTI4LWIxNTUtMmQ1MGNkNTdlNTI2OjEyMzQ1Njc4OQ==' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials'

### Relevant log output

```shell
{
    "error": "invalid_client",
    "error_description": "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method).",
    "status_code": 401
}
```

### Relevant configuration

```yml
export SECRETS_SYSTEM=nnXz52aAjQRIiID7ov4tRH5HZuKfQk9t
export SERVE_ADMIN_HOST=localhost
export SERVE_ADMIN_CORS_DEBUG=true
export SERVE_ADMIN_ACCESS_LOG_DISABLE_FOR_HEALTH=false
export SERVE_ADMIN_TLS_ENABLED=false
export SERVE_PUBLIC_HOST=localhost
export SERVE_PUBLIC_ACCESS_LOG_DISABLE_FOR_HEALTH=false
export DSN="mysql://root:@tcp(docker.for.mac.localhost:3306)/hydra"
export OAUTH2_INCLUDE_LEGACY_ERROR_FIELDS=true
```

### Version

v1.10.6

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker

### Additional Context

GET http://localhost:9001/clients/604d1876-3929-4928-b155-2d50cd57e526

```
{
    "client_id": "604d1876-3929-4928-b155-2d50cd57e526",
    "client_name": "Test2",
    "redirect_uris": [],
    "grant_types": [
        "client_credentials"
    ],
    "response_types": [],
    "scope": "offline_access offline openid",
    "audience": [],
    "owner": "",
    "policy_uri": "",
    "allowed_cors_origins": [],
    "tos_uri": "",
    "client_uri": "",
    "logo_uri": "",
    "contacts": [],
    "client_secret_expires_at": 0,
    "subject_type": "public",
    "jwks": {},
    "token_endpoint_auth_method": "client_secret_basic",
    "userinfo_signed_response_alg": "none",
    "created_at": "2021-12-23T14:21:43Z",
    "updated_at": "2021-12-27T06:38:32Z",
    "metadata": {}
}
```

**Comment by aeneasr** [comment]
Thank you for opening an issue. You already created a discussion on this topic 23 hours ago here: https://github.com/ory/hydra/discussions/2904

I will close this issue because you are not experiencing a bug and there is a discussion open already. Someone from community will be able to help you (@vinckr for example). What you observe is most likely an issue with your set up, the way you use commands, a typo, or something else. Client authentication is tested extensively in unit, functional, integration, and e2e tests. Ory Hydra is 6+ years old, runs live in over 25.000 deployments around the world and handles over 5+ billion API requests every month. If something essential such as client authentication didn't work, it would already have been noticed :)

Thank you for your understanding!
