### ISSUE TITLE
Add key rotation policy for JSON Web Token Signing Keys

### ISSUE THREAD

**Issue by aarmam** [ory/hydra#3408]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We would like to let clients know about upcoming key rotation. Similar issue has been rised by #2535 
Under the current policy, the addition of a new key immediately revokes the previous key. With the proposed change, the older key will be used until it is deleted, at which point the newer key will be used.

### Describe your ideal solution

Introduce configuration propery:

```yaml
strategies:
    jwks_key_rotation_policy: forward_key_rotation/backward_key_rotation
```

Where forward_key_rotation would be default and currently used newest key first strategy. To implement this we would change how key manager sorts the keys returned
https://github.com/ory/hydra/blob/master/persistence/sql/persister_jwk.go#L158
https://github.com/ory/hydra/blob/master/persistence/sql/persister_jwk.go#L131
To implement sorting in HSM we have to introduce special key id prefixing format, that will help sorting keys as PKCS11 does not guarantee the ordering of the keys.

### Workarounds or alternatives

-

### Version

2.x

### Additional Context

Will implement it if accepted!

**Comment by tilgovi** [comment]
This would be still be quite useful. The closest workaround I've found is to add another key set to the list of key sets that Hydra serves at the well known endpoint, e.g. `hydra.jwt.access-token.next`. Later, copy this key to `hydra.jwt.access-token` to start signing with it.

Unfortunately, there's no easy way to do that copy atomically without manipulating the database directly.

But maybe there's an idea in here about implementation. Rather than any kind of policy, just give operators an atomic operation for moving a key between sets, maybe.
