### ISSUE TITLE
Hydra URLs mounted to a subpath

### ISSUE THREAD

**Issue by waynerobinson** [ory/hydra#352]
Allow Hydra URLs to be mounted to a subpath so that instead of URLs like:

`/oauth2/auth`
`/oauth2/token`

It will respond to URLs like:

`/some/other/path/oauth2/auth`
`/some/other/path/oauth2/token`

This makes proxying from a single domain easier as no URL rewriting is necessary.

URL rewriting can effect the `redir` portion of a challenge token being set incorrectly and issues with the session cookie used to prevent replay attacks.

Easiest implementation option is probably to allow for the prefix to be set via a global config option.

**Comment by janekolszak** [comment]
I think the easiest is to have a separate subdomain for hydra.

**Comment by waynerobinson** [comment]
That doesn't work in all cases. For example, our app has self-service custom branding. To avoid users ever seeing our internal Hydra domain flash, it and each of our services need to exist on the customer's own (single) domain.

**Comment by arekkas** [comment]
Most API gateways can solve this, in the example of kong, `preserve_host` and `strip_tag` are the settings to look for.

Closing as this has been open for a while and you guys have fixed this.

**Comment by wyattanderson** [comment]
We're generally able to run Hydra behind a proxy that strips out the prefix, but we're running into the issue mentioned here:

> URL rewriting can effect the redir portion of a challenge token being set incorrectly and issues with the session cookie used to prevent replay attacks.

The `openid-configuration` response includes the right `authorization_endpoint` field by concatenating `ISSUER` (`https://foo.bar.com/hydra`) with the URL (see [the source](https://github.com/ory/hydra/blob/48c229b62af56ab16f26e827b221b9e04bb0c077/oauth2/handler.go#L139)), but the `redirectToConsent` function just [uses the incoming request](https://github.com/ory/hydra/blob/48c229b62af56ab16f26e827b221b9e04bb0c077/oauth2/handler.go#L376-L379), which isn't accurate since we strip `/hydra/` from the URL at the load balancer.

Would it make sense to update `redirectToConsent` to construct the redirect URL from the configured issuer URL and the `AuthPath`?

**Comment by arekkas** [comment]
Yeah that makes sense, I would also add a check whether or not the endpoint is https or not (disallow https). Would you mind doing a PR?

**Comment by wyattanderson** [comment]
I'll work on a PR.

> I would also add a check whether or not the endpoint is https or not (disallow https)

Why would we want to disallow HTTPS? Or do you mean we should respect the `ForcedHTTP` option?

**Comment by arekkas** [comment]
Sorry, I meant disallow http for everything except localhost

**Comment by wyattanderson** [comment]
What do you think about performing that check (`ISSUER` have `https` scheme, unless host is `localhost` **and** `dangerous-force-http` is set) on startup, say, in `cmd/server/handler.go` or when the config is parsed in `cmd/root.go`?
