### ISSUE TITLE
hydra db migration: CREATE INDEX CONCURRENTLY

### ISSUE THREAD

**Issue by harvhan** [ory/hydra#3892]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe your problem

During one of our deployments, we noticed that the hydra db migration ['CREATE INDEX' step](https://github.com/ory/hydra/blob/b0270ad721ffb6ff7814dc2bf039ec806de95e49/persistence/sql/migrations/20240612222110000001_add_oauth2_expires_at_indices.up.sql#L1) took too long while holding a write lock to the database. Since this is a database serving live traffic, we cannot afford to have a long down time.

### Describe your ideal solution

Can we consider adding `CONCURRENTLY` to the [CREATE INDEX sql statements](https://github.com/ory/hydra/blob/b0270ad721ffb6ff7814dc2bf039ec806de95e49/persistence/sql/migrations/20240612222110000001_add_oauth2_expires_at_indices.up.sql#L1), so that the db can still function while creating the indexes?

### Workarounds or alternatives

We considered running hydra janitor commands regularly, but it didn't help much and we also really want to have near zero down time.

### Version

master

**Comment by aeneasr** [comment]
We can consider that in the future, but online migrations are generally not available when self-hosting open source and only available when using a build from our Ory Enterprise License. This is because releases in OSS bundle many changes, and releases with OEL happening step with releases to Ory Network which are generally online.

While adding concurrent index creation will solve write locks, it may cause other issues with index hints afaik.

**Comment by aeneasr** [comment]
I'm closing this as not planned but we will consider better index management for PG/MYSQL in the future
