### ISSUE TITLE
Warden and Introspection: field mismatch

### ISSUE THREAD

**Issue by matteosuppo** [ory/hydra#402]
A request to /introspect yields

```
{  
   "active":true,
   "scope":"profile:core profile:public",
   "client_id":"arduinoday",
   "sub":"5b40751b-42cf-4d7c-9250-6ddc6ad8ad73",
   "exp":1490624509,
   "iat":1490620909,
   "aud":"arduinoday"
}
```

while a request to /warden/token/allowed yields

```
{  
   "sub":"5b40751b-42cf-4d7c-9250-6ddc6ad8ad73",
   "scopes":[  
      "profile:core",
      "profile:public"
   ],
   "iss":"hydra.localhost",
   "aud":"arduinoday",
   "iat":"2017-03-27T13:21:49.188993Z",
   "exp":"2017-03-27T14:21:49.188993Z",
   "ext":null,
   "allowed":true
}
```

Notice that the fields `iat` and `exp` are different. In one case hydra is returning an integer and in the other a date.

Since they're basically the same wouldn't it be better if they were consistent?

**Comment by arekkas** [comment]
Hey @matteosuppo , glad you're still around :)

The reasoning behind using `"2017-03-27T13:21:49.188993Z"` is that this is actually the standard json time format while the integers are actually 64bit floats (because javascript) that represent unix timestamps. Unfortunately, the unix timestamp format is what the introspection spec says. You're right that this represents an inconsistency but I think that the warden endpoint should serve the "best" & interoperable data possible, which is why this format was chosen.

I'm open to changing this, although I need to be convinced first :)

**Comment by matteosuppo** [comment]
(We're finally putting the hydra-powered authorization system in production by the way: https://auth.arduino.cc)

Actually it's not a big deal, I was just wondering if you knew about that inconsistency. Handling it on my side it's a matter of minutes, so I don't think it makes sense to change hydra api. I'm closing it, ok?

**Comment by arekkas** [comment]
Awesome, thats cool news! I would be interested in your deployment and how hydra performs, could we maybe jump on a quick discussion on gitter for this? :) It would help me weight future features and issues!
