### ISSUE TITLE
oauth2: refresh openid connect id token via refresh_token grant

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#556]

**Comment by wyattanderson** [comment]
Is this cooperative with the consent application or does it just reissue the same ID token again and again?

**Comment by arekkas** [comment]
Same ID token as [per spec](http://openid.net/specs/openid-connect-core-1_0.html#RefreshTokens)

**Comment by wyattanderson** [comment]
I'm happy to contribute some work to this, but I think it'd be much more useful to be able to update any of the [standard claims](http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) such as `email`, `name`, etc. in addition to any custom-supplied claims that may change over the lifetime of the token (e.g. LDAP group membership, custom permissions, etc.), or even have the option for the consent application to reject issuance of a new ID token at all (is it even possible for the consent app to revoke tokens right now or are they effectively permanent?).

Of course we can work around this with a userinfo endpoint, but if I want to pass around a signed JWT to various services over the lifetime of the request, it would greatly simplify things if we could rely on the ID token alone and the standard refresh flow.

**Comment by arekkas** [comment]
This will be difficult to implement, because once the consent flow is done it is not possible to update access token data or id token data, as the requests to `/oauth2/token` usually don't happen from the user's browser.

ID Tokens can be refreshed indefinitely, unless an access or refresh token are revoked that belong to the same consent request id. ID Tokens have an expiry time (which is why you need to refresh them obviously).

On a side note, as a User I would not want to wait an hour until my LDAP memberships are updated. I think you'll have a better system with a dynamic endpoint.

**Comment by wyattanderson** [comment]
Right, what I'm suggesting is an optional way for Hydra to directly access an API endpoint on the consent application, secured by a signed request with the challenge keys or something, to fetch a new set of claims to add to the refreshed ID token. Hydra/Fosite would still be responsible for validating the refresh/access tokens, ensuring adherence to the spec in terms of not updating the `sub`, `iss`, etc.

**Comment by arekkas** [comment]
I'm trying to avoid a REST api dependency from hydra to the consent app as it significantly increases the integration complexity. Since the userinfo endpoint is standardized and it sounds like you need one, my next step would be to explore that route. Maybe at some point there will be support for userinfo within Hydra and then you'll be able to simply switch your API service to hydra.

**Comment by wyattanderson** [comment]
Understandable. Thanks!

**Comment by wyattanderson** [comment]
I want to revisit this again and get your thoughts; I think the current behavior is at best not very useful and at worst dangerous because there's no way for anyone but the end-user to revoke tokens if a refresh token has been issued. Since token revocation requires the token itself, it's impossible for the identity provider to tell Hydra to stop issuing new tokens and new identity tokens in this scheme. Aside from the need for updating claims in the ID token, it should be possible for the operators of the identity provider to somehow "lock out" a user's account.

That's why I think it's worth having an optional integration point between Hydra and the consent application to allow an out-of-band consent refresh to correspond with the issuance of new tokens, and the ability to trigger an [`invalid_grant`](https://tools.ietf.org/html/rfc6749#section-5.2) error response per spec if the refresh token has been revoked. I don't think this dramatically increases the integration complexity if it's optional.

**Comment by arekkas** [comment]
Yes, the case is definitely valid. I will take a look once the workload here is a bit less, in about 3 weeks.

**Comment by arekkas** [comment]
So, coming back to this issue. The first concern you raise (revoking refresh tokens without user presence) is very valid and will be addressed as part of #304 which has now been bumped to 1.0 milestone.

What I don't fully understand is the integration point. So here, Hydra would query the consent app for claims to be put in the ID Token? What kind of data are we looking at here? Is there a spec that talks about updated claims? Access tokens for example don't receive new claims as per spec, apart from expiration date.

**Comment by wyattanderson** [comment]
> specs which say explicitly what core claims may be updated and which ones may not: http://openid.net/specs/openid-connect-core-1_0.html#RefreshTokens

I don't read this as a whitelisting of which claims may change. I read it as saying "certain claims must remain stable because changing them doesn't make sense (such as changing the `sub`, i.e. changing the identity of the logged-in user mid-session) or would present a security risk". Of course things like `iss`, `sub`, `aud` must not change, but per the spec:

> otherwise, the same rules apply as apply when issuing an ID Token at the time of the original authentication.

So, we have [standard claims](http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) such as `email`, `name`, `profile`, `picture`, etc. which could change (imagine you change your email address, display name, profile information, etc. and want that change reflected in the refresh token).

Then, we have [additional claims](http://openid.net/specs/openid-connect-core-1_0.html#AdditionalClaims):

> other Claims MAY be used in conjunction with the standard Claims. When using such Claims, it is RECOMMENDED that collision-resistant names be used for the Claim Names, as described in the JSON Web Token (JWT) [JWT] specification. Alternatively, Private Claim Names can be safely used when naming conflicts are unlikely to arise, as described in the JWT specification.

This, of course, is part of the draw of JWTs: the ability to set arbitrary, application- and context-dependent claims in the token to facilitate a microservices architecture. Even without non-standard claims, I think there's an argument to be made for changing _standard_ OIDC claims since they can and will change over the lifetime of a user session.

Because Hydra lets the consent app sign arbitrary claims into the ID token with `id_ext`, I think we _must_ support cooperative updating of those claims somehow. Maybe not on every refresh, but ideally there would be at least some way for the consent app or IdP to say "invalidate the ID token for this user" and require a claim refresh (but not necessarily a reauthentication) on next refresh.

**Comment by supercairos** [comment]
Hi, I'm wondering if updating the id token claims is still not possible today ?
