### ISSUE TITLE
docs: /warden/allowed do not fully specify security parameters

### ISSUE THREAD

**Issue by mozbhearsum** [ory/hydra#565]
On http://docs.hydra13.apiary.io/#reference/warden/wardenallowed/check-if-a-subject-is-allowed-to-do-something the text description for the endpoint says:

> Checks if an arbitrary subject is allowed to perform an action on a resource. This endpoint requires a subject, a resource name, an action name and a context.If the subject is not allowed to perform the action on the resource, this endpoint returns a 200 response with 

From this, I can see that the endpoint must be provided the subject, resource, action, and context. However, it's not clear what these parameters should be called. Some of the examples use "action" and "subject", but there is nothing that shows exactly what all of the parameters are named, and what they look like.

**Comment by arekkas** [comment]
Unfortunately, this is due to bad design choices by apiary, oauth2 is properly referenced as you can see in the screenshot:

<img width="797" alt="bildschirmfoto 2017-07-29 um 10 07 05" src="https://user-images.githubusercontent.com/3372410/28743250-c672f65a-7445-11e7-9a67-4e617a3553e1.png">

<img width="877" alt="bildschirmfoto 2017-07-29 um 10 08 44" src="https://user-images.githubusercontent.com/3372410/28743255-f11150be-7445-11e7-9c5d-593ad4199e90.png">

I will try to follow up with apiary on this, which might take some time.

Also, for some reason, it says implicit OAuth2 which isn't correct.

**Comment by mozbhearsum** [comment]
Hm, I'm not sure I understand what you mean. Even if I click "oauth2" I don't see any thing about subject, action, etc. It's also not in the Body section of the console, eg: https://screenshots.firefox.com/mAe0p0DKGJeqzZcA/docs.hydra13.apiary.io.

**Comment by arekkas** [comment]
That's what I meant that it's a bug in Apiary (the api docs provider) :)

**Comment by arekkas** [comment]
this has now moved and is no longer an issue
