### ISSUE TITLE
Multi stage build process removes the ability to shell into hydra container

### ISSUE THREAD

**Issue by mabruneau** [ory/hydra#657]
With the latest Dockerfile changes (tag:v.0.10.0-alpha.18), making use of the multi stage builder pattern, it appears that its not possible to shell into the container anymore.

Not sure if there is a way to only COPY a static version of /bin/sh to keep the size low. 

In the meantime, I updated my version of the Dockerfile to replace the second FROM instruction (FROM scratch) to FROM busybox.

**Comment by arekkas** [comment]
This is very much intentional, not only does it reduce the docker image's size, it's also unnecessary, even risky, to run production systems with shell. You can do everything you did before (which is executing hydra commands) by overriding the command:

```
$ docker run oryd/hydra help
$ docker run oryd/hydra clients create
$ docker run oryd/hydra ...
```

If you need shell access to the container you will need to use your own Dockerfile definition for now.

**Comment by mabruneau** [comment]
OK, thank you for the detailed explanation. 

I was following the tutorial (https://ory.gitbooks.io/hydra/content/tutorial.html) and got bugged down to the line where it's requested to connect in the container.

**Comment by arekkas** [comment]
Yes, the tutorial hasn't been updated to the latest docker images, which is also why the .13 tag is used! :)
