### ISSUE TITLE
Trailing slash redirect strips directories from path

### ISSUE THREAD

**Issue by pnicolcev-tulipretail** [ory/hydra#723]
When a client leaves a trailing slash on the end of an endpoint Hydra redirects with a 307 to, for eg.
`Location: /oauth2/token`

We deploy Hydra under a directory eg. `/hydra` and the redirect is missing this from the start of the path.

The URLs in the discovery endpoint are all correct (and stripping the slash from the end of my client resolves the issue).

**Comment by arekkas** [comment]
Thank you for your report.

This is caused by httprouter which automatically redirects thinks like `domain.com//foo` to `domain.com/foo` and `domain.com/foo/` to `domain.com/foo`. As it does so based on the route name, not the issuer url, there is no clear way to resolve this issue in that specific case.

As all endpoints are properly advertised in the discovery endpoints, this will be a nofix, unless serious concerns arise, or practical ideas on how to resolve it.
